# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class GenericSecretAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :data_json, T::String
    attribute :path, T::String
    attribute? :delete_all_versions, T::Bool.optional
    attribute? :disable_read, T::Bool.optional
    attribute? :namespace, T::String.optional
  end
end
