# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class AwsAuthBackendCertAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :aws_public_cert, T::String
    attribute :cert_name, T::String
    attribute? :backend, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :type, T::String.optional
  end
end
