# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class TransformTransformationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :name, T::String
    attribute :path, T::String
    attribute? :allowed_roles, T::Array.of(T::String).optional
    attribute? :deletion_allowed, T::Bool.optional
    attribute? :masking_character, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :template, T::String.optional
    attribute? :tweak_source, T::String.optional
    attribute? :type, T::String.optional
  end
end
