# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class TokenAuthBackendRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :role_name, T::String
    attribute? :allowed_entity_aliases, T::Array.of(T::String).optional
    attribute? :allowed_policies, T::Array.of(T::String).optional
    attribute? :allowed_policies_glob, T::Array.of(T::String).optional
    attribute? :disallowed_policies, T::Array.of(T::String).optional
    attribute? :disallowed_policies_glob, T::Array.of(T::String).optional
    attribute? :namespace, T::String.optional
    attribute? :orphan, T::Bool.optional
    attribute? :path_suffix, T::String.optional
    attribute? :renewable, T::Bool.optional
    attribute? :token_bound_cidrs, T::Array.of(T::String).optional
    attribute? :token_explicit_max_ttl, T::Float.optional
    attribute? :token_max_ttl, T::Float.optional
    attribute? :token_no_default_policy, T::Bool.optional
    attribute? :token_num_uses, T::Float.optional
    attribute? :token_period, T::Float.optional
    attribute? :token_policies, T::Array.of(T::String).optional
    attribute? :token_ttl, T::Float.optional
    attribute? :token_type, T::String.optional
  end
end
