# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class GcpSecretImpersonatedAccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :backend, T::String
    attribute :impersonated_account, T::String
    attribute :service_account_email, T::String
    attribute? :namespace, T::String.optional
    attribute? :token_scopes, T::Array.of(T::String).optional
  end
end
