# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class IdentityOidcKeyAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :name, T::String
    attribute? :algorithm, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :rotation_period, T::Float.optional
    attribute? :verification_ttl, T::Float.optional
  end
end
