# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class SecretsSyncAwsDestinationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :name, T::String
    attribute? :access_key_id, T::String.optional
    attribute? :custom_tags, T::Hash.optional
    attribute? :external_id, T::String.optional
    attribute? :granularity, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :region, T::String.optional
    attribute? :role_arn, T::String.optional
    attribute? :secret_access_key, T::String.optional
  end
end
