# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_database_secret_backend_static_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultDatabaseSecretBackendStaticRole
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_database_secret_backend_static_role,
      attributes_class: Vault::Types::DatabaseSecretBackendStaticRoleAttributes,
      outputs: { id: :id },
      map: [:backend, :db_name, :name, :username],
      map_present: [:credential_config, :namespace, :rotation_period, :rotation_schedule, :rotation_statements, :rotation_window, :self_managed_password],
      map_bool: [:skip_import_rotation]
  end
  module Vault
    include VaultDatabaseSecretBackendStaticRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
