# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_pki_secret_backend_config_issuers/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultPkiSecretBackendConfigIssuers
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_pki_secret_backend_config_issuers,
      attributes_class: Vault::Types::PkiSecretBackendConfigIssuersAttributes,
      outputs: { id: :id },
      map: [:backend],
      map_present: [:default, :namespace]
  end
  module Vault
    include VaultPkiSecretBackendConfigIssuers
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
