# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_cert_auth_backend_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultCertAuthBackendRole
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_cert_auth_backend_role,
      attributes_class: Vault::Types::CertAuthBackendRoleAttributes,
      outputs: { id: :id },
      map: [:certificate, :name],
      map_present: [:allowed_organizational_units, :backend, :namespace, :ocsp_ca_certificates, :ocsp_servers_override, :token_bound_cidrs, :token_explicit_max_ttl, :token_max_ttl, :token_num_uses, :token_period, :token_policies, :token_ttl, :token_type],
      map_bool: [:token_no_default_policy]
  end
  module Vault
    include VaultCertAuthBackendRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
