# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class IdentityMfaTotpAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :issuer, T::String
    attribute? :algorithm, T::String.optional
    attribute? :digits, T::Float.optional
    attribute? :key_size, T::Float.optional
    attribute? :max_validation_attempts, T::Float.optional
    attribute? :namespace, T::String.optional
    attribute? :period, T::Float.optional
    attribute? :skew, T::Float.optional
  end
end
