# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_aws_auth_backend_role_tag/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultAwsAuthBackendRoleTag
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_aws_auth_backend_role_tag,
      attributes_class: Vault::Types::AwsAuthBackendRoleTagAttributes,
      outputs: { id: :id },
      map: [:role],
      map_present: [:backend, :instance_id, :max_ttl, :namespace, :policies],
      map_bool: [:allow_instance_migration, :disallow_reauthentication]
  end
  module Vault
    include VaultAwsAuthBackendRoleTag
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
