# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_identity_oidc_scope/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultIdentityOidcScope
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_identity_oidc_scope,
      attributes_class: Vault::Types::IdentityOidcScopeAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:description, :namespace, :template]
  end
  module Vault
    include VaultIdentityOidcScope
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
