# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class TokenAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute? :display_name, T::String.optional
    attribute? :explicit_max_ttl, T::String.optional
    attribute? :metadata, T::Hash.optional
    attribute? :namespace, T::String.optional
    attribute? :no_default_policy, T::Bool.optional
    attribute? :period, T::String.optional
    attribute? :policies, T::Array.of(T::String).optional
    attribute? :renew_increment, T::Float.optional
    attribute? :renew_min_lease, T::Float.optional
    attribute? :role_name, T::String.optional
    attribute? :ttl, T::String.optional
    attribute? :wrapping_ttl, T::String.optional
  end
end
