# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_terraform_cloud_secret_creds/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultTerraformCloudSecretCreds
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_terraform_cloud_secret_creds,
      attributes_class: Vault::Types::TerraformCloudSecretCredsAttributes,
      outputs: { id: :id },
      map: [:backend, :role],
      map_present: [:namespace]
  end
  module Vault
    include VaultTerraformCloudSecretCreds
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
