# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class PkiSecretBackendConfigClusterAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :backend, T::String
    attribute? :aia_path, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :path, T::String.optional
  end
end
