# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class KmipSecretScopeAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :path, T::String
    attribute :scope, T::String
    attribute? :force, T::Bool.optional
    attribute? :namespace, T::String.optional
  end
end
