# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class PkiSecretBackendConfigCmpv2Attributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :backend, T::String
    attribute? :authenticators, T::Array.of(T::Hash).optional
    attribute? :default_path_policy, T::String.optional
    attribute? :disabled_validations, T::Array.of(T::String).optional
    attribute? :enable_sentinel_parsing, T::Bool.optional
    attribute? :enabled, T::Bool.optional
    attribute? :namespace, T::String.optional
  end
end
