# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_kmip_secret_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultKmipSecretRole
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_kmip_secret_role,
      attributes_class: Vault::Types::KmipSecretRoleAttributes,
      outputs: { id: :id },
      map: [:path, :role, :scope],
      map_present: [:namespace, :tls_client_key_bits, :tls_client_key_type, :tls_client_ttl]
  end
  module Vault
    include VaultKmipSecretRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
