# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_pki_secret_backend_role/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultPkiSecretBackendRole
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_pki_secret_backend_role,
      attributes_class: Vault::Types::PkiSecretBackendRoleAttributes,
      outputs: { id: :id },
      map: [:backend, :name],
      map_present: [:allowed_domains, :allowed_other_sans, :allowed_serial_numbers, :allowed_uri_sans, :allowed_user_ids, :country, :ext_key_usage, :ext_key_usage_oids, :key_bits, :key_type, :locality, :namespace, :not_after, :organization, :ou, :policy_identifier, :policy_identifiers, :postal_code, :province, :street_address],
      map_bool: [:allow_any_name, :allow_bare_domains, :allow_glob_domains, :allow_ip_sans, :allow_localhost, :allow_subdomains, :allow_wildcard_certificates, :allowed_domains_template, :basic_constraints_valid_for_non_ca, :client_flag, :code_signing_flag, :email_protection_flag, :enforce_hostnames, :generate_lease, :no_store, :no_store_metadata, :require_cn, :server_flag, :use_csr_common_name, :use_csr_sans, :use_pss]
  end
  module Vault
    include VaultPkiSecretBackendRole
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
