# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_identity_group_policies/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultIdentityGroupPolicies
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_identity_group_policies,
      attributes_class: Vault::Types::IdentityGroupPoliciesAttributes,
      outputs: { id: :id },
      map: [:group_id, :policies],
      map_present: [:namespace],
      map_bool: [:exclusive]
  end
  module Vault
    include VaultIdentityGroupPolicies
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
