# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_audit_request_header/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultAuditRequestHeader
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_audit_request_header,
      attributes_class: Vault::Types::AuditRequestHeaderAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:namespace],
      map_bool: [:hmac]
  end
  module Vault
    include VaultAuditRequestHeader
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
