# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class JwtAuthBackendAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute? :bound_issuer, T::String.optional
    attribute? :default_role, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disable_remount, T::Bool.optional
    attribute? :jwks_ca_pem, T::String.optional
    attribute? :jwks_url, T::String.optional
    attribute? :jwt_supported_algs, T::Array.of(T::String).optional
    attribute? :jwt_validation_pubkeys, T::Array.of(T::String).optional
    attribute? :local, T::Bool.optional
    attribute? :namespace, T::String.optional
    attribute? :namespace_in_state, T::Bool.optional
    attribute? :oidc_client_id, T::String.optional
    attribute? :oidc_client_secret, T::String.optional
    attribute? :oidc_discovery_ca_pem, T::String.optional
    attribute? :oidc_discovery_url, T::String.optional
    attribute? :oidc_response_mode, T::String.optional
    attribute? :oidc_response_types, T::Array.of(T::String).optional
    attribute? :path, T::String.optional
    attribute? :provider_config, T::Hash.optional
    attribute? :type, T::String.optional
  end
end
