# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class IdentityGroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute? :external_member_entity_ids, T::Bool.optional
    attribute? :external_member_group_ids, T::Bool.optional
    attribute? :external_policies, T::Bool.optional
    attribute? :member_entity_ids, T::Array.of(T::String).optional
    attribute? :member_group_ids, T::Array.of(T::String).optional
    attribute? :metadata, T::Hash.optional
    attribute? :namespace, T::String.optional
    attribute? :policies, T::Array.of(T::String).optional
    attribute? :type, T::String.optional
  end
end
