# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_identity_entity_alias/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultIdentityEntityAlias
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_identity_entity_alias,
      attributes_class: Vault::Types::IdentityEntityAliasAttributes,
      outputs: { id: :id },
      map: [:canonical_id, :mount_accessor, :name],
      map_present: [:custom_metadata, :namespace]
  end
  module Vault
    include VaultIdentityEntityAlias
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
