# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class SecretsSyncVercelDestinationAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :access_token, T::String
    attribute :deployment_environments, T::Array.of(T::String)
    attribute :name, T::String
    attribute :project_id, T::String
    attribute? :granularity, T::String.optional
    attribute? :namespace, T::String.optional
    attribute? :team_id, T::String.optional
  end
end
