# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class IdentityOidcKeyAllowedClientIdAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :allowed_client_id, T::String
    attribute :key_name, T::String
    attribute? :namespace, T::String.optional
  end
end
