# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_database_secret_backend_connection/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultDatabaseSecretBackendConnection
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_database_secret_backend_connection,
      attributes_class: Vault::Types::DatabaseSecretBackendConnectionAttributes,
      outputs: { id: :id },
      map: [:backend, :name],
      map_present: [:allowed_roles, :cassandra, :couchbase, :data, :elasticsearch, :hana, :influxdb, :mongodb, :mongodbatlas, :mssql, :mysql, :mysql_aurora, :mysql_legacy, :mysql_rds, :namespace, :oracle, :postgresql, :redis, :redis_elasticache, :redshift, :root_rotation_statements, :rotation_period, :rotation_schedule, :rotation_window, :snowflake],
      map_bool: [:disable_automated_rotation, :verify_connection]
  end
  module Vault
    include VaultDatabaseSecretBackendConnection
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
