# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class DatabaseSecretBackendConnectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :backend, T::String
    attribute :name, T::String
    attribute? :allowed_roles, T::Array.of(T::String).optional
    attribute? :cassandra, T::Array.of(T::Hash).optional
    attribute? :couchbase, T::Array.of(T::Hash).optional
    attribute? :data, T::Hash.optional
    attribute? :disable_automated_rotation, T::Bool.optional
    attribute? :elasticsearch, T::Array.of(T::Hash).optional
    attribute? :hana, T::Array.of(T::Hash).optional
    attribute? :influxdb, T::Array.of(T::Hash).optional
    attribute? :mongodb, T::Array.of(T::Hash).optional
    attribute? :mongodbatlas, T::Array.of(T::Hash).optional
    attribute? :mssql, T::Array.of(T::Hash).optional
    attribute? :mysql, T::Array.of(T::Hash).optional
    attribute? :mysql_aurora, T::Array.of(T::Hash).optional
    attribute? :mysql_legacy, T::Array.of(T::Hash).optional
    attribute? :mysql_rds, T::Array.of(T::Hash).optional
    attribute? :namespace, T::String.optional
    attribute? :oracle, T::Array.of(T::Hash).optional
    attribute? :postgresql, T::Array.of(T::Hash).optional
    attribute? :redis, T::Array.of(T::Hash).optional
    attribute? :redis_elasticache, T::Array.of(T::Hash).optional
    attribute? :redshift, T::Array.of(T::Hash).optional
    attribute? :root_rotation_statements, T::Array.of(T::String).optional
    attribute? :rotation_period, T::Float.optional
    attribute? :rotation_schedule, T::String.optional
    attribute? :rotation_window, T::Float.optional
    attribute? :snowflake, T::Array.of(T::Hash).optional
    attribute? :verify_connection, T::Bool.optional
  end
end
