# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class KubernetesSecretBackendAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :path, T::String
    attribute? :allowed_managed_keys, T::Array.of(T::String).optional
    attribute? :allowed_response_headers, T::Array.of(T::String).optional
    attribute? :delegated_auth_accessors, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
    attribute? :disable_local_ca_jwt, T::Bool.optional
    attribute? :external_entropy_access, T::Bool.optional
    attribute? :identity_token_key, T::String.optional
    attribute? :kubernetes_ca_cert, T::String.optional
    attribute? :kubernetes_host, T::String.optional
    attribute? :listing_visibility, T::String.optional
    attribute? :local, T::Bool.optional
    attribute? :namespace, T::String.optional
    attribute? :options, T::Hash.optional
    attribute? :passthrough_request_headers, T::Array.of(T::String).optional
    attribute? :plugin_version, T::String.optional
    attribute? :service_account_jwt, T::String.optional
  end
end
