# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class ManagedKeysAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute? :aws, T::Array.of(T::Hash).optional
    attribute? :azure, T::Array.of(T::Hash).optional
    attribute? :namespace, T::String.optional
    attribute? :pkcs, T::Array.of(T::Hash).optional
  end
end
