# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class PkiSecretBackendIssuerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :backend, T::String
    attribute :issuer_ref, T::String
    attribute? :crl_distribution_points, T::Array.of(T::String).optional
    attribute? :disable_critical_extension_checks, T::Bool.optional
    attribute? :disable_name_checks, T::Bool.optional
    attribute? :disable_name_constraint_checks, T::Bool.optional
    attribute? :disable_path_length_checks, T::Bool.optional
    attribute? :enable_aia_url_templating, T::Bool.optional
    attribute? :issuer_name, T::String.optional
    attribute? :issuing_certificates, T::Array.of(T::String).optional
    attribute? :manual_chain, T::Array.of(T::String).optional
    attribute? :namespace, T::String.optional
    attribute? :ocsp_servers, T::Array.of(T::String).optional
  end
end
