# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_policy/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultPolicy
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_policy,
      attributes_class: Vault::Types::PolicyAttributes,
      outputs: { id: :id },
      map: [:name, :policy],
      map_present: [:namespace]
  end
  module Vault
    include VaultPolicy
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
