# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_aws_auth_backend_config_identity/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultAwsAuthBackendConfigIdentity
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_aws_auth_backend_config_identity,
      attributes_class: Vault::Types::AwsAuthBackendConfigIdentityAttributes,
      outputs: { id: :id },
      map_present: [:backend, :ec2_alias, :ec2_metadata, :iam_alias, :iam_metadata, :namespace]
  end
  module Vault
    include VaultAwsAuthBackendConfigIdentity
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
