# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_ldap_auth_backend_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultLdapAuthBackendUser
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_ldap_auth_backend_user,
      attributes_class: Vault::Types::LdapAuthBackendUserAttributes,
      outputs: { id: :id },
      map: [:username],
      map_present: [:backend, :namespace]
  end
  module Vault
    include VaultLdapAuthBackendUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
