# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class IdentityMfaDuoAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :api_hostname, T::String
    attribute :integration_key, T::String
    attribute :secret_key, T::String
    attribute? :namespace, T::String.optional
    attribute? :push_info, T::String.optional
    attribute? :use_passcode, T::Bool.optional
    attribute? :username_format, T::String.optional
  end
end
