# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_pki_secret_backend_config_est/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultPkiSecretBackendConfigEst
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_pki_secret_backend_config_est,
      attributes_class: Vault::Types::PkiSecretBackendConfigEstAttributes,
      outputs: { id: :id },
      map: [:backend],
      map_present: [:authenticators, :default_path_policy, :label_to_path_policy, :namespace],
      map_bool: [:default_mount, :enable_sentinel_parsing, :enabled]
  end
  module Vault
    include VaultPkiSecretBackendConfigEst
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
