# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_pki_secret_backend_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultPkiSecretBackendKey
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_pki_secret_backend_key,
      attributes_class: Vault::Types::PkiSecretBackendKeyAttributes,
      outputs: { id: :id },
      map: [:backend, :type],
      map_present: [:key_name, :managed_key_id, :managed_key_name, :namespace]
  end
  module Vault
    include VaultPkiSecretBackendKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
