# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class GcpSecretBackendAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute? :credentials, T::String.optional
    attribute? :default_lease_ttl_seconds, T::Float.optional
    attribute? :description, T::String.optional
    attribute? :disable_automated_rotation, T::Bool.optional
    attribute? :disable_remount, T::Bool.optional
    attribute? :identity_token_audience, T::String.optional
    attribute? :identity_token_key, T::String.optional
    attribute? :identity_token_ttl, T::Float.optional
    attribute? :local, T::Bool.optional
    attribute? :max_lease_ttl_seconds, T::Float.optional
    attribute? :namespace, T::String.optional
    attribute? :path, T::String.optional
    attribute? :rotation_period, T::Float.optional
    attribute? :rotation_schedule, T::String.optional
    attribute? :rotation_window, T::Float.optional
    attribute? :service_account_email, T::String.optional
  end
end
