# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class RabbitmqSecretBackendAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :connection_uri, T::String
    attribute :password, T::String
    attribute :username, T::String
    attribute? :description, T::String.optional
    attribute? :disable_remount, T::Bool.optional
    attribute? :namespace, T::String.optional
    attribute? :password_policy, T::String.optional
    attribute? :path, T::String.optional
    attribute? :username_template, T::String.optional
    attribute? :verify_connection, T::Bool.optional
  end
end
