# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Vault::Types
  include Dry.Types()

  class IdentityOidcAssignmentAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Vault::Types

    attribute :name, T::String
    attribute? :entity_ids, T::Array.of(T::String).optional
    attribute? :group_ids, T::Array.of(T::String).optional
    attribute? :namespace, T::String.optional
  end
end
