# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/vault_kv_secret_backend_v2/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module VaultKvSecretBackendV2
    include Pangea::Resources::ResourceBuilder

    define_resource :vault_kv_secret_backend_v2,
      attributes_class: Vault::Types::KvSecretBackendV2Attributes,
      outputs: { id: :id },
      map: [:mount],
      map_present: [:delete_version_after, :namespace]
  end
  module Vault
    include VaultKvSecretBackendV2
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Vault)
