# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_pki_secret_backend_config_est resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultPkiSecretBackendConfigEst do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value' } }

  describe ':vault_pki_secret_backend_config_est' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'test')
        validate_required_attributes(config, [:backend])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_pki_secret_backend_config_est('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_pki_secret_backend_config_est)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_pki_secret_backend_config_est('test', required_attrs)

        expect(ref.id).to eq("${vault_pki_secret_backend_config_est.test.id}")
        expect(ref.audit_fields).to eq("${vault_pki_secret_backend_config_est.test.audit_fields}")
        expect(ref.last_updated).to eq("${vault_pki_secret_backend_config_est.test.last_updated}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'test')
        expect(config).not_to have_key('audit_fields')
        expect(config).not_to have_key('last_updated')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ authenticators: [{ 'key1' => 'val1' }], default_mount: true, default_path_policy: 'test-value', enable_sentinel_parsing: true, enabled: true, label_to_path_policy: { 'key1' => 'val1' }, namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'full')
        expect(config).to have_key('authenticators')
        expect(config).to have_key('default_mount')
        expect(config).to have_key('default_path_policy')
        expect(config).to have_key('enable_sentinel_parsing')
        expect(config).to have_key('enabled')
        expect(config).to have_key('label_to_path_policy')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes authenticators when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(authenticators: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('authenticators')
      end

      it 'omits authenticators when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('authenticators')
      end
      it 'includes default_mount when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(default_mount: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('default_mount')
      end

      it 'omits default_mount when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('default_mount')
      end
      it 'includes default_path_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(default_path_policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('default_path_policy')
      end

      it 'omits default_path_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('default_path_policy')
      end
      it 'includes enable_sentinel_parsing when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(enable_sentinel_parsing: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('enable_sentinel_parsing')
      end

      it 'omits enable_sentinel_parsing when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('enable_sentinel_parsing')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes label_to_path_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(label_to_path_policy: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('label_to_path_policy')
      end

      it 'omits label_to_path_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('label_to_path_policy')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts default_mount=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(default_mount: val)
          synth.vault_pki_secret_backend_config_est("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', "bool_#{val}")
          expect(config['default_mount']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_sentinel_parsing=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_sentinel_parsing: val)
          synth.vault_pki_secret_backend_config_est("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', "bool_#{val}")
          expect(config['enable_sentinel_parsing']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.vault_pki_secret_backend_config_est("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_est', 'typed')
        expect(config['backend']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_est('first', required_attrs)
        synth.vault_pki_secret_backend_config_est('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_pki_secret_backend_config_est')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_pki_secret_backend_config_est,
    method: :vault_pki_secret_backend_config_est,
    required_attrs: { backend: 'test-value' },
    expected_outputs: [:id, :audit_fields, :last_updated],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:default_mount, :enable_sentinel_parsing, :enabled]
end
