# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_identity_entity_policies resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultIdentityEntityPolicies do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { entity_id: 'test-value', policies: ['test-value'] } }

  describe ':vault_identity_entity_policies' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'test')
        validate_required_attributes(config, [:entity_id, :policies])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_identity_entity_policies('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_identity_entity_policies)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_identity_entity_policies('test', required_attrs)

        expect(ref.id).to eq("${vault_identity_entity_policies.test.id}")
        expect(ref.entity_name).to eq("${vault_identity_entity_policies.test.entity_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'test')
        expect(config).not_to have_key('entity_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ exclusive: true, namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'full')
        expect(config).to have_key('exclusive')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes exclusive when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('opt', required_attrs.merge(exclusive: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'opt')
        expect(config).to have_key('exclusive')
      end

      it 'omits exclusive when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'minimal')
        expect(config).not_to have_key('exclusive')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts exclusive=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(exclusive: val)
          synth.vault_identity_entity_policies("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_identity_entity_policies', "bool_#{val}")
          expect(config['exclusive']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_entity_policies', 'typed')
        expect(config['entity_id']).to be_a(String)
        expect(config['policies']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_entity_policies('first', required_attrs)
        synth.vault_identity_entity_policies('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_identity_entity_policies')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_identity_entity_policies,
    method: :vault_identity_entity_policies,
    required_attrs: { entity_id: 'test-value', policies: ['test-value'] },
    expected_outputs: [:id, :entity_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:exclusive]
end
