# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_identity_oidc_key_allowed_client_id resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultIdentityOidcKeyAllowedClientId do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { allowed_client_id: 'test-value', key_name: 'test-value' } }

  describe ':vault_identity_oidc_key_allowed_client_id' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_oidc_key_allowed_client_id('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_identity_oidc_key_allowed_client_id', 'test')
        validate_required_attributes(config, [:allowed_client_id, :key_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_identity_oidc_key_allowed_client_id('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_identity_oidc_key_allowed_client_id)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_identity_oidc_key_allowed_client_id('test', required_attrs)

        expect(ref.id).to eq("${vault_identity_oidc_key_allowed_client_id.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_oidc_key_allowed_client_id('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_oidc_key_allowed_client_id', 'full')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_oidc_key_allowed_client_id('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_oidc_key_allowed_client_id', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_oidc_key_allowed_client_id('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_oidc_key_allowed_client_id', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_oidc_key_allowed_client_id('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_oidc_key_allowed_client_id', 'typed')
        expect(config['allowed_client_id']).to be_a(String)
        expect(config['key_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_oidc_key_allowed_client_id('first', required_attrs)
        synth.vault_identity_oidc_key_allowed_client_id('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_identity_oidc_key_allowed_client_id')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_identity_oidc_key_allowed_client_id,
    method: :vault_identity_oidc_key_allowed_client_id,
    required_attrs: { allowed_client_id: 'test-value', key_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
