# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_kubernetes_secret_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultKubernetesSecretBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value', name: 'test-value' } }

  describe ':vault_kubernetes_secret_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'test')
        validate_required_attributes(config, [:backend, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_kubernetes_secret_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_kubernetes_secret_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_kubernetes_secret_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_kubernetes_secret_backend_role.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_kubernetes_namespace_selector: 'test-value', allowed_kubernetes_namespaces: ['test-value'], extra_annotations: { 'key1' => 'val1' }, extra_labels: { 'key1' => 'val1' }, generated_role_rules: 'test-value', kubernetes_role_name: 'test-value', kubernetes_role_type: 'test-value', name_template: 'test-value', namespace: 'test-value', service_account_name: 'test-value', token_default_ttl: 3.14, token_max_ttl: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'full')
        expect(config).to have_key('allowed_kubernetes_namespace_selector')
        expect(config).to have_key('allowed_kubernetes_namespaces')
        expect(config).to have_key('extra_annotations')
        expect(config).to have_key('extra_labels')
        expect(config).to have_key('generated_role_rules')
        expect(config).to have_key('kubernetes_role_name')
        expect(config).to have_key('kubernetes_role_type')
        expect(config).to have_key('name_template')
        expect(config).to have_key('namespace')
        expect(config).to have_key('service_account_name')
        expect(config).to have_key('token_default_ttl')
        expect(config).to have_key('token_max_ttl')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_kubernetes_namespace_selector when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(allowed_kubernetes_namespace_selector: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_kubernetes_namespace_selector')
      end

      it 'omits allowed_kubernetes_namespace_selector when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_kubernetes_namespace_selector')
      end
      it 'includes allowed_kubernetes_namespaces when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(allowed_kubernetes_namespaces: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_kubernetes_namespaces')
      end

      it 'omits allowed_kubernetes_namespaces when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_kubernetes_namespaces')
      end
      it 'includes extra_annotations when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(extra_annotations: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('extra_annotations')
      end

      it 'omits extra_annotations when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('extra_annotations')
      end
      it 'includes extra_labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(extra_labels: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('extra_labels')
      end

      it 'omits extra_labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('extra_labels')
      end
      it 'includes generated_role_rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(generated_role_rules: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('generated_role_rules')
      end

      it 'omits generated_role_rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('generated_role_rules')
      end
      it 'includes kubernetes_role_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(kubernetes_role_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('kubernetes_role_name')
      end

      it 'omits kubernetes_role_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('kubernetes_role_name')
      end
      it 'includes kubernetes_role_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(kubernetes_role_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('kubernetes_role_type')
      end

      it 'omits kubernetes_role_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('kubernetes_role_type')
      end
      it 'includes name_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(name_template: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('name_template')
      end

      it 'omits name_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('name_template')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes service_account_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(service_account_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('service_account_name')
      end

      it 'omits service_account_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('service_account_name')
      end
      it 'includes token_default_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(token_default_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('token_default_ttl')
      end

      it 'omits token_default_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('token_default_ttl')
      end
      it 'includes token_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('opt', required_attrs.merge(token_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'opt')
        expect(config).to have_key('token_max_ttl')
      end

      it 'omits token_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'minimal')
        expect(config).not_to have_key('token_max_ttl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_kubernetes_secret_backend_role', 'typed')
        expect(config['backend']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_kubernetes_secret_backend_role('first', required_attrs)
        synth.vault_kubernetes_secret_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_kubernetes_secret_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_kubernetes_secret_backend_role,
    method: :vault_kubernetes_secret_backend_role,
    required_attrs: { backend: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
