# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_aws_auth_backend_login resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultAwsAuthBackendLogin do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':vault_aws_auth_backend_login' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_aws_auth_backend_login('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_aws_auth_backend_login)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_aws_auth_backend_login('test', required_attrs)

        expect(ref.id).to eq("${vault_aws_auth_backend_login.test.id}")
        expect(ref.accessor).to eq("${vault_aws_auth_backend_login.test.accessor}")
        expect(ref.auth_type).to eq("${vault_aws_auth_backend_login.test.auth_type}")
        expect(ref.client_token).to eq("${vault_aws_auth_backend_login.test.client_token}")
        expect(ref.lease_duration).to eq("${vault_aws_auth_backend_login.test.lease_duration}")
        expect(ref.lease_start_time).to eq("${vault_aws_auth_backend_login.test.lease_start_time}")
        expect(ref.metadata).to eq("${vault_aws_auth_backend_login.test.metadata}")
        expect(ref.nonce).to eq("${vault_aws_auth_backend_login.test.nonce}")
        expect(ref.policies).to eq("${vault_aws_auth_backend_login.test.policies}")
        expect(ref.renewable).to eq("${vault_aws_auth_backend_login.test.renewable}")
        expect(ref.role).to eq("${vault_aws_auth_backend_login.test.role}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'test')
        expect(config).not_to have_key('accessor')
        expect(config).not_to have_key('auth_type')
        expect(config).not_to have_key('client_token')
        expect(config).not_to have_key('lease_duration')
        expect(config).not_to have_key('lease_start_time')
        expect(config).not_to have_key('metadata')
        expect(config).not_to have_key('nonce')
        expect(config).not_to have_key('policies')
        expect(config).not_to have_key('renewable')
        expect(config).not_to have_key('role')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ backend: 'test-value', iam_http_request_method: 'test-value', iam_request_body: 'test-value', iam_request_headers: 'test-value', iam_request_url: 'test-value', identity: 'test-value', namespace: 'test-value', pkcs7: 'test-value', signature: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'full')
        expect(config).to have_key('backend')
        expect(config).to have_key('iam_http_request_method')
        expect(config).to have_key('iam_request_body')
        expect(config).to have_key('iam_request_headers')
        expect(config).to have_key('iam_request_url')
        expect(config).to have_key('identity')
        expect(config).to have_key('namespace')
        expect(config).to have_key('pkcs7')
        expect(config).to have_key('signature')
      end
    end

    context 'optional attributes' do
      it 'includes backend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(backend: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('backend')
      end

      it 'omits backend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('backend')
      end
      it 'includes iam_http_request_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(iam_http_request_method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('iam_http_request_method')
      end

      it 'omits iam_http_request_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('iam_http_request_method')
      end
      it 'includes iam_request_body when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(iam_request_body: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('iam_request_body')
      end

      it 'omits iam_request_body when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('iam_request_body')
      end
      it 'includes iam_request_headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(iam_request_headers: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('iam_request_headers')
      end

      it 'omits iam_request_headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('iam_request_headers')
      end
      it 'includes iam_request_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(iam_request_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('iam_request_url')
      end

      it 'omits iam_request_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('iam_request_url')
      end
      it 'includes identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(identity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('identity')
      end

      it 'omits identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('identity')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes pkcs7 when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(pkcs7: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('pkcs7')
      end

      it 'omits pkcs7 when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('pkcs7')
      end
      it 'includes signature when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('opt', required_attrs.merge(signature: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'opt')
        expect(config).to have_key('signature')
      end

      it 'omits signature when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'minimal')
        expect(config).not_to have_key('signature')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:client_token]
        expect(sensitive_fields).to include(:client_token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_auth_backend_login', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_auth_backend_login('first', required_attrs)
        synth.vault_aws_auth_backend_login('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_aws_auth_backend_login')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_aws_auth_backend_login,
    method: :vault_aws_auth_backend_login,
    required_attrs: {},
    expected_outputs: [:id, :accessor, :auth_type, :client_token, :lease_duration, :lease_start_time, :metadata, :nonce, :policies, :renewable, :role],
    sensitive_fields: [:client_token],
    immutable_fields: [],
    boolean_fields: []
end
