# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_generic_secret resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultGenericSecret do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { data_json: 'test-value', path: 'test-value' } }

  describe ':vault_generic_secret' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_generic_secret', 'test')
        validate_required_attributes(config, [:data_json, :path])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_generic_secret('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_generic_secret)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_generic_secret('test', required_attrs)

        expect(ref.id).to eq("${vault_generic_secret.test.id}")
        expect(ref.data).to eq("${vault_generic_secret.test.data}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_generic_secret', 'test')
        expect(config).not_to have_key('data')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ delete_all_versions: true, disable_read: true, namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_generic_secret', 'full')
        expect(config).to have_key('delete_all_versions')
        expect(config).to have_key('disable_read')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes delete_all_versions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('opt', required_attrs.merge(delete_all_versions: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_generic_secret', 'opt')
        expect(config).to have_key('delete_all_versions')
      end

      it 'omits delete_all_versions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_generic_secret', 'minimal')
        expect(config).not_to have_key('delete_all_versions')
      end
      it 'includes disable_read when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('opt', required_attrs.merge(disable_read: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_generic_secret', 'opt')
        expect(config).to have_key('disable_read')
      end

      it 'omits disable_read when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_generic_secret', 'minimal')
        expect(config).not_to have_key('disable_read')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_generic_secret', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_generic_secret', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:data_json, :data]
        expect(sensitive_fields).to include(:data_json)
        expect(sensitive_fields).to include(:data)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delete_all_versions=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_all_versions: val)
          synth.vault_generic_secret("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_generic_secret', "bool_#{val}")
          expect(config['delete_all_versions']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_read=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_read: val)
          synth.vault_generic_secret("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_generic_secret', "bool_#{val}")
          expect(config['disable_read']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_generic_secret', 'typed')
        expect(config['data_json']).to be_a(String)
        expect(config['path']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_generic_secret('first', required_attrs)
        synth.vault_generic_secret('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_generic_secret')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_generic_secret,
    method: :vault_generic_secret,
    required_attrs: { data_json: 'test-value', path: 'test-value' },
    expected_outputs: [:id, :data],
    sensitive_fields: [:data_json, :data],
    immutable_fields: [],
    boolean_fields: [:delete_all_versions, :disable_read]
end
