# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_ssh_secret_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultSshSecretBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value', key_type: 'test-value', name: 'test-value' } }

  describe ':vault_ssh_secret_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'test')
        validate_required_attributes(config, [:backend, :key_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_ssh_secret_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_ssh_secret_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_ssh_secret_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_ssh_secret_backend_role.test.id}")
        expect(ref.algorithm_signer).to eq("${vault_ssh_secret_backend_role.test.algorithm_signer}")
        expect(ref.allowed_domains_template).to eq("${vault_ssh_secret_backend_role.test.allowed_domains_template}")
        expect(ref.max_ttl).to eq("${vault_ssh_secret_backend_role.test.max_ttl}")
        expect(ref.not_before_duration).to eq("${vault_ssh_secret_backend_role.test.not_before_duration}")
        expect(ref.ttl).to eq("${vault_ssh_secret_backend_role.test.ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'test')
        expect(config).not_to have_key('algorithm_signer')
        expect(config).not_to have_key('allowed_domains_template')
        expect(config).not_to have_key('max_ttl')
        expect(config).not_to have_key('not_before_duration')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_bare_domains: true, allow_empty_principals: true, allow_host_certificates: true, allow_subdomains: true, allow_user_certificates: true, allow_user_key_ids: true, allowed_critical_options: 'test-value', allowed_domains: 'test-value', allowed_extensions: 'test-value', allowed_user_key_config: [{ 'key1' => 'val1' }], allowed_users: 'test-value', allowed_users_template: true, cidr_list: 'test-value', default_critical_options: { 'key1' => 'val1' }, default_extensions: { 'key1' => 'val1' }, default_user: 'test-value', default_user_template: true, key_id_format: 'test-value', namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'full')
        expect(config).to have_key('allow_bare_domains')
        expect(config).to have_key('allow_empty_principals')
        expect(config).to have_key('allow_host_certificates')
        expect(config).to have_key('allow_subdomains')
        expect(config).to have_key('allow_user_certificates')
        expect(config).to have_key('allow_user_key_ids')
        expect(config).to have_key('allowed_critical_options')
        expect(config).to have_key('allowed_domains')
        expect(config).to have_key('allowed_extensions')
        expect(config).to have_key('allowed_user_key_config')
        expect(config).to have_key('allowed_users')
        expect(config).to have_key('allowed_users_template')
        expect(config).to have_key('cidr_list')
        expect(config).to have_key('default_critical_options')
        expect(config).to have_key('default_extensions')
        expect(config).to have_key('default_user')
        expect(config).to have_key('default_user_template')
        expect(config).to have_key('key_id_format')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes allow_bare_domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allow_bare_domains: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allow_bare_domains')
      end

      it 'omits allow_bare_domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allow_bare_domains')
      end
      it 'includes allow_empty_principals when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allow_empty_principals: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allow_empty_principals')
      end

      it 'omits allow_empty_principals when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allow_empty_principals')
      end
      it 'includes allow_host_certificates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allow_host_certificates: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allow_host_certificates')
      end

      it 'omits allow_host_certificates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allow_host_certificates')
      end
      it 'includes allow_subdomains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allow_subdomains: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allow_subdomains')
      end

      it 'omits allow_subdomains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allow_subdomains')
      end
      it 'includes allow_user_certificates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allow_user_certificates: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allow_user_certificates')
      end

      it 'omits allow_user_certificates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allow_user_certificates')
      end
      it 'includes allow_user_key_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allow_user_key_ids: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allow_user_key_ids')
      end

      it 'omits allow_user_key_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allow_user_key_ids')
      end
      it 'includes allowed_critical_options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allowed_critical_options: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_critical_options')
      end

      it 'omits allowed_critical_options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_critical_options')
      end
      it 'includes allowed_domains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allowed_domains: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_domains')
      end

      it 'omits allowed_domains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_domains')
      end
      it 'includes allowed_extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allowed_extensions: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_extensions')
      end

      it 'omits allowed_extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_extensions')
      end
      it 'includes allowed_user_key_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allowed_user_key_config: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_user_key_config')
      end

      it 'omits allowed_user_key_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_user_key_config')
      end
      it 'includes allowed_users when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allowed_users: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_users')
      end

      it 'omits allowed_users when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_users')
      end
      it 'includes allowed_users_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(allowed_users_template: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('allowed_users_template')
      end

      it 'omits allowed_users_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_users_template')
      end
      it 'includes cidr_list when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(cidr_list: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('cidr_list')
      end

      it 'omits cidr_list when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('cidr_list')
      end
      it 'includes default_critical_options when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(default_critical_options: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('default_critical_options')
      end

      it 'omits default_critical_options when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('default_critical_options')
      end
      it 'includes default_extensions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(default_extensions: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('default_extensions')
      end

      it 'omits default_extensions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('default_extensions')
      end
      it 'includes default_user when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(default_user: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('default_user')
      end

      it 'omits default_user when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('default_user')
      end
      it 'includes default_user_template when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(default_user_template: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('default_user_template')
      end

      it 'omits default_user_template when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('default_user_template')
      end
      it 'includes key_id_format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(key_id_format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('key_id_format')
      end

      it 'omits key_id_format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('key_id_format')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_bare_domains=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_bare_domains: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allow_bare_domains']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_empty_principals=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_empty_principals: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allow_empty_principals']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_host_certificates=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_host_certificates: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allow_host_certificates']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_subdomains=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_subdomains: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allow_subdomains']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_user_certificates=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_user_certificates: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allow_user_certificates']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allow_user_key_ids=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_user_key_ids: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allow_user_key_ids']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts allowed_users_template=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allowed_users_template: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['allowed_users_template']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts default_user_template=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(default_user_template: val)
          synth.vault_ssh_secret_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', "bool_#{val}")
          expect(config['default_user_template']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ssh_secret_backend_role', 'typed')
        expect(config['backend']).to be_a(String)
        expect(config['key_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ssh_secret_backend_role('first', required_attrs)
        synth.vault_ssh_secret_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_ssh_secret_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_ssh_secret_backend_role,
    method: :vault_ssh_secret_backend_role,
    required_attrs: { backend: 'test-value', key_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :algorithm_signer, :allowed_domains_template, :max_ttl, :not_before_duration, :ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_bare_domains, :allow_empty_principals, :allow_host_certificates, :allow_subdomains, :allow_user_certificates, :allow_user_key_ids, :allowed_users_template, :default_user_template]
end
