# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_transform_template resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultTransformTemplate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', path: 'test-value' } }

  describe ':vault_transform_template' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_transform_template', 'test')
        validate_required_attributes(config, [:name, :path])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_transform_template('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_transform_template)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_transform_template('test', required_attrs)

        expect(ref.id).to eq("${vault_transform_template.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alphabet: 'test-value', decode_formats: { 'key1' => 'val1' }, encode_format: 'test-value', namespace: 'test-value', pattern: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_transform_template', 'full')
        expect(config).to have_key('alphabet')
        expect(config).to have_key('decode_formats')
        expect(config).to have_key('encode_format')
        expect(config).to have_key('namespace')
        expect(config).to have_key('pattern')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes alphabet when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('opt', required_attrs.merge(alphabet: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'opt')
        expect(config).to have_key('alphabet')
      end

      it 'omits alphabet when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'minimal')
        expect(config).not_to have_key('alphabet')
      end
      it 'includes decode_formats when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('opt', required_attrs.merge(decode_formats: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'opt')
        expect(config).to have_key('decode_formats')
      end

      it 'omits decode_formats when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'minimal')
        expect(config).not_to have_key('decode_formats')
      end
      it 'includes encode_format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('opt', required_attrs.merge(encode_format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'opt')
        expect(config).to have_key('encode_format')
      end

      it 'omits encode_format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'minimal')
        expect(config).not_to have_key('encode_format')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes pattern when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('opt', required_attrs.merge(pattern: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'opt')
        expect(config).to have_key('pattern')
      end

      it 'omits pattern when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'minimal')
        expect(config).not_to have_key('pattern')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transform_template', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_transform_template', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['path']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transform_template('first', required_attrs)
        synth.vault_transform_template('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_transform_template')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_transform_template,
    method: :vault_transform_template,
    required_attrs: { name: 'test-value', path: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
