# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_approle_auth_backend_login resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultApproleAuthBackendLogin do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { role_id: 'test-value' } }

  describe ':vault_approle_auth_backend_login' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'test')
        validate_required_attributes(config, [:role_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_approle_auth_backend_login('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_approle_auth_backend_login)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_approle_auth_backend_login('test', required_attrs)

        expect(ref.id).to eq("${vault_approle_auth_backend_login.test.id}")
        expect(ref.accessor).to eq("${vault_approle_auth_backend_login.test.accessor}")
        expect(ref.client_token).to eq("${vault_approle_auth_backend_login.test.client_token}")
        expect(ref.lease_duration).to eq("${vault_approle_auth_backend_login.test.lease_duration}")
        expect(ref.lease_started).to eq("${vault_approle_auth_backend_login.test.lease_started}")
        expect(ref.metadata).to eq("${vault_approle_auth_backend_login.test.metadata}")
        expect(ref.policies).to eq("${vault_approle_auth_backend_login.test.policies}")
        expect(ref.renewable).to eq("${vault_approle_auth_backend_login.test.renewable}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'test')
        expect(config).not_to have_key('accessor')
        expect(config).not_to have_key('client_token')
        expect(config).not_to have_key('lease_duration')
        expect(config).not_to have_key('lease_started')
        expect(config).not_to have_key('metadata')
        expect(config).not_to have_key('policies')
        expect(config).not_to have_key('renewable')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ backend: 'test-value', namespace: 'test-value', secret_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'full')
        expect(config).to have_key('backend')
        expect(config).to have_key('namespace')
        expect(config).to have_key('secret_id')
      end
    end

    context 'optional attributes' do
      it 'includes backend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('opt', required_attrs.merge(backend: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'opt')
        expect(config).to have_key('backend')
      end

      it 'omits backend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'minimal')
        expect(config).not_to have_key('backend')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes secret_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('opt', required_attrs.merge(secret_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'opt')
        expect(config).to have_key('secret_id')
      end

      it 'omits secret_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'minimal')
        expect(config).not_to have_key('secret_id')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:client_token, :secret_id]
        expect(sensitive_fields).to include(:client_token)
        expect(sensitive_fields).to include(:secret_id)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_approle_auth_backend_login', 'typed')
        expect(config['role_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_login('first', required_attrs)
        synth.vault_approle_auth_backend_login('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_approle_auth_backend_login')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_approle_auth_backend_login,
    method: :vault_approle_auth_backend_login,
    required_attrs: { role_id: 'test-value' },
    expected_outputs: [:id, :accessor, :client_token, :lease_duration, :lease_started, :metadata, :policies, :renewable],
    sensitive_fields: [:client_token, :secret_id],
    immutable_fields: [],
    boolean_fields: []
end
