# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_okta_auth_backend resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultOktaAuthBackend do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { organization: 'test-value' } }

  describe ':vault_okta_auth_backend' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'test')
        validate_required_attributes(config, [:organization])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_okta_auth_backend('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_okta_auth_backend)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_okta_auth_backend('test', required_attrs)

        expect(ref.id).to eq("${vault_okta_auth_backend.test.id}")
        expect(ref.accessor).to eq("${vault_okta_auth_backend.test.accessor}")
        expect(ref.group).to eq("${vault_okta_auth_backend.test.group}")
        expect(ref.user).to eq("${vault_okta_auth_backend.test.user}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'test')
        expect(config).not_to have_key('accessor')
        expect(config).not_to have_key('group')
        expect(config).not_to have_key('user')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ base_url: 'test-value', bypass_okta_mfa: true, description: 'test-value', disable_remount: true, max_ttl: 'test-value', namespace: 'test-value', path: 'test-value', token: 'test-value', token_bound_cidrs: ['test-value'], token_explicit_max_ttl: 3.14, token_max_ttl: 3.14, token_no_default_policy: true, token_num_uses: 3.14, token_period: 3.14, token_policies: ['test-value'], token_ttl: 3.14, token_type: 'test-value', ttl: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'full')
        expect(config).to have_key('base_url')
        expect(config).to have_key('bypass_okta_mfa')
        expect(config).to have_key('description')
        expect(config).to have_key('disable_remount')
        expect(config).to have_key('max_ttl')
        expect(config).to have_key('namespace')
        expect(config).to have_key('path')
        expect(config).to have_key('token')
        expect(config).to have_key('token_bound_cidrs')
        expect(config).to have_key('token_explicit_max_ttl')
        expect(config).to have_key('token_max_ttl')
        expect(config).to have_key('token_no_default_policy')
        expect(config).to have_key('token_num_uses')
        expect(config).to have_key('token_period')
        expect(config).to have_key('token_policies')
        expect(config).to have_key('token_ttl')
        expect(config).to have_key('token_type')
        expect(config).to have_key('ttl')
      end
    end

    context 'optional attributes' do
      it 'includes base_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(base_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('base_url')
      end

      it 'omits base_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('base_url')
      end
      it 'includes bypass_okta_mfa when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(bypass_okta_mfa: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('bypass_okta_mfa')
      end

      it 'omits bypass_okta_mfa when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('bypass_okta_mfa')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes disable_remount when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(disable_remount: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('disable_remount')
      end

      it 'omits disable_remount when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('disable_remount')
      end
      it 'includes max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(max_ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('max_ttl')
      end

      it 'omits max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('max_ttl')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('path')
      end

      it 'omits path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('path')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token')
      end
      it 'includes token_bound_cidrs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_bound_cidrs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_bound_cidrs')
      end

      it 'omits token_bound_cidrs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_bound_cidrs')
      end
      it 'includes token_explicit_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_explicit_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_explicit_max_ttl')
      end

      it 'omits token_explicit_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_explicit_max_ttl')
      end
      it 'includes token_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_max_ttl')
      end

      it 'omits token_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_max_ttl')
      end
      it 'includes token_no_default_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_no_default_policy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_no_default_policy')
      end

      it 'omits token_no_default_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_no_default_policy')
      end
      it 'includes token_num_uses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_num_uses: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_num_uses')
      end

      it 'omits token_num_uses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_num_uses')
      end
      it 'includes token_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_period')
      end

      it 'omits token_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_period')
      end
      it 'includes token_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_policies')
      end

      it 'omits token_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_policies')
      end
      it 'includes token_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_ttl')
      end

      it 'omits token_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_ttl')
      end
      it 'includes token_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(token_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('token_type')
      end

      it 'omits token_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('token_type')
      end
      it 'includes ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('opt', required_attrs.merge(ttl: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'opt')
        expect(config).to have_key('ttl')
      end

      it 'omits ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'minimal')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts bypass_okta_mfa=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(bypass_okta_mfa: val)
          synth.vault_okta_auth_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_okta_auth_backend', "bool_#{val}")
          expect(config['bypass_okta_mfa']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_remount=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_remount: val)
          synth.vault_okta_auth_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_okta_auth_backend', "bool_#{val}")
          expect(config['disable_remount']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts token_no_default_policy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(token_no_default_policy: val)
          synth.vault_okta_auth_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_okta_auth_backend', "bool_#{val}")
          expect(config['token_no_default_policy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_okta_auth_backend', 'typed')
        expect(config['organization']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_okta_auth_backend('first', required_attrs)
        synth.vault_okta_auth_backend('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_okta_auth_backend')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_okta_auth_backend,
    method: :vault_okta_auth_backend,
    required_attrs: { organization: 'test-value' },
    expected_outputs: [:id, :accessor, :group, :user],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: [:bypass_okta_mfa, :disable_remount, :token_no_default_policy]
end
