# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_aws_secret_backend resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultAwsSecretBackend do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':vault_aws_secret_backend' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_aws_secret_backend('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_aws_secret_backend)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_aws_secret_backend('test', required_attrs)

        expect(ref.id).to eq("${vault_aws_secret_backend.test.id}")
        expect(ref.default_lease_ttl_seconds).to eq("${vault_aws_secret_backend.test.default_lease_ttl_seconds}")
        expect(ref.identity_token_ttl).to eq("${vault_aws_secret_backend.test.identity_token_ttl}")
        expect(ref.max_lease_ttl_seconds).to eq("${vault_aws_secret_backend.test.max_lease_ttl_seconds}")
        expect(ref.region).to eq("${vault_aws_secret_backend.test.region}")
        expect(ref.username_template).to eq("${vault_aws_secret_backend.test.username_template}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'test')
        expect(config).not_to have_key('default_lease_ttl_seconds')
        expect(config).not_to have_key('identity_token_ttl')
        expect(config).not_to have_key('max_lease_ttl_seconds')
        expect(config).not_to have_key('region')
        expect(config).not_to have_key('username_template')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access_key: 'test-value', description: 'test-value', disable_automated_rotation: true, disable_remount: true, iam_endpoint: 'test-value', identity_token_audience: 'test-value', identity_token_key: 'test-value', local: true, namespace: 'test-value', path: 'test-value', role_arn: 'test-value', rotation_period: 3.14, rotation_schedule: 'test-value', rotation_window: 3.14, secret_key: 'test-value', sts_endpoint: 'test-value', sts_fallback_endpoints: ['test-value'], sts_fallback_regions: ['test-value'], sts_region: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'full')
        expect(config).to have_key('access_key')
        expect(config).to have_key('description')
        expect(config).to have_key('disable_automated_rotation')
        expect(config).to have_key('disable_remount')
        expect(config).to have_key('iam_endpoint')
        expect(config).to have_key('identity_token_audience')
        expect(config).to have_key('identity_token_key')
        expect(config).to have_key('local')
        expect(config).to have_key('namespace')
        expect(config).to have_key('path')
        expect(config).to have_key('role_arn')
        expect(config).to have_key('rotation_period')
        expect(config).to have_key('rotation_schedule')
        expect(config).to have_key('rotation_window')
        expect(config).to have_key('secret_key')
        expect(config).to have_key('sts_endpoint')
        expect(config).to have_key('sts_fallback_endpoints')
        expect(config).to have_key('sts_fallback_regions')
        expect(config).to have_key('sts_region')
      end
    end

    context 'optional attributes' do
      it 'includes access_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(access_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('access_key')
      end

      it 'omits access_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('access_key')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes disable_automated_rotation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(disable_automated_rotation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('disable_automated_rotation')
      end

      it 'omits disable_automated_rotation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('disable_automated_rotation')
      end
      it 'includes disable_remount when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(disable_remount: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('disable_remount')
      end

      it 'omits disable_remount when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('disable_remount')
      end
      it 'includes iam_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(iam_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('iam_endpoint')
      end

      it 'omits iam_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('iam_endpoint')
      end
      it 'includes identity_token_audience when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(identity_token_audience: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('identity_token_audience')
      end

      it 'omits identity_token_audience when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('identity_token_audience')
      end
      it 'includes identity_token_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(identity_token_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('identity_token_key')
      end

      it 'omits identity_token_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('identity_token_key')
      end
      it 'includes local when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(local: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('local')
      end

      it 'omits local when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('local')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('path')
      end

      it 'omits path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('path')
      end
      it 'includes role_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(role_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('role_arn')
      end

      it 'omits role_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('role_arn')
      end
      it 'includes rotation_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(rotation_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('rotation_period')
      end

      it 'omits rotation_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('rotation_period')
      end
      it 'includes rotation_schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(rotation_schedule: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('rotation_schedule')
      end

      it 'omits rotation_schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('rotation_schedule')
      end
      it 'includes rotation_window when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(rotation_window: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('rotation_window')
      end

      it 'omits rotation_window when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('rotation_window')
      end
      it 'includes secret_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(secret_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('secret_key')
      end

      it 'omits secret_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('secret_key')
      end
      it 'includes sts_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(sts_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('sts_endpoint')
      end

      it 'omits sts_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('sts_endpoint')
      end
      it 'includes sts_fallback_endpoints when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(sts_fallback_endpoints: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('sts_fallback_endpoints')
      end

      it 'omits sts_fallback_endpoints when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('sts_fallback_endpoints')
      end
      it 'includes sts_fallback_regions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(sts_fallback_regions: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('sts_fallback_regions')
      end

      it 'omits sts_fallback_regions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('sts_fallback_regions')
      end
      it 'includes sts_region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('opt', required_attrs.merge(sts_region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'opt')
        expect(config).to have_key('sts_region')
      end

      it 'omits sts_region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'minimal')
        expect(config).not_to have_key('sts_region')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:access_key, :secret_key]
        expect(sensitive_fields).to include(:access_key)
        expect(sensitive_fields).to include(:secret_key)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_automated_rotation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_automated_rotation: val)
          synth.vault_aws_secret_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_aws_secret_backend', "bool_#{val}")
          expect(config['disable_automated_rotation']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_remount=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_remount: val)
          synth.vault_aws_secret_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_aws_secret_backend', "bool_#{val}")
          expect(config['disable_remount']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts local=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(local: val)
          synth.vault_aws_secret_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_aws_secret_backend', "bool_#{val}")
          expect(config['local']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_secret_backend', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend('first', required_attrs)
        synth.vault_aws_secret_backend('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_aws_secret_backend')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_aws_secret_backend,
    method: :vault_aws_secret_backend,
    required_attrs: {},
    expected_outputs: [:id, :default_lease_ttl_seconds, :identity_token_ttl, :max_lease_ttl_seconds, :region, :username_template],
    sensitive_fields: [:access_key, :secret_key],
    immutable_fields: [],
    boolean_fields: [:disable_automated_rotation, :disable_remount, :local]
end
