# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_pki_secret_backend_config_ca resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultPkiSecretBackendConfigCa do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value', pem_bundle: 'test-value' } }

  describe ':vault_pki_secret_backend_config_ca' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_ca('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_ca', 'test')
        validate_required_attributes(config, [:backend, :pem_bundle])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_pki_secret_backend_config_ca('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_pki_secret_backend_config_ca)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_pki_secret_backend_config_ca('test', required_attrs)

        expect(ref.id).to eq("${vault_pki_secret_backend_config_ca.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_ca('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_ca', 'full')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_ca('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_ca', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_ca('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_ca', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:pem_bundle]
        expect(sensitive_fields).to include(:pem_bundle)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_ca('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_pki_secret_backend_config_ca', 'typed')
        expect(config['backend']).to be_a(String)
        expect(config['pem_bundle']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_pki_secret_backend_config_ca('first', required_attrs)
        synth.vault_pki_secret_backend_config_ca('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_pki_secret_backend_config_ca')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_pki_secret_backend_config_ca,
    method: :vault_pki_secret_backend_config_ca,
    required_attrs: { backend: 'test-value', pem_bundle: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:pem_bundle],
    immutable_fields: [],
    boolean_fields: []
end
