# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_cert_auth_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultCertAuthBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { certificate: 'test-value', name: 'test-value' } }

  describe ':vault_cert_auth_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'test')
        validate_required_attributes(config, [:certificate, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_cert_auth_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_cert_auth_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_cert_auth_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_cert_auth_backend_role.test.id}")
        expect(ref.allowed_common_names).to eq("${vault_cert_auth_backend_role.test.allowed_common_names}")
        expect(ref.allowed_dns_sans).to eq("${vault_cert_auth_backend_role.test.allowed_dns_sans}")
        expect(ref.allowed_email_sans).to eq("${vault_cert_auth_backend_role.test.allowed_email_sans}")
        expect(ref.allowed_names).to eq("${vault_cert_auth_backend_role.test.allowed_names}")
        expect(ref.allowed_uri_sans).to eq("${vault_cert_auth_backend_role.test.allowed_uri_sans}")
        expect(ref.display_name).to eq("${vault_cert_auth_backend_role.test.display_name}")
        expect(ref.ocsp_enabled).to eq("${vault_cert_auth_backend_role.test.ocsp_enabled}")
        expect(ref.ocsp_fail_open).to eq("${vault_cert_auth_backend_role.test.ocsp_fail_open}")
        expect(ref.ocsp_query_all_servers).to eq("${vault_cert_auth_backend_role.test.ocsp_query_all_servers}")
        expect(ref.required_extensions).to eq("${vault_cert_auth_backend_role.test.required_extensions}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'test')
        expect(config).not_to have_key('allowed_common_names')
        expect(config).not_to have_key('allowed_dns_sans')
        expect(config).not_to have_key('allowed_email_sans')
        expect(config).not_to have_key('allowed_names')
        expect(config).not_to have_key('allowed_uri_sans')
        expect(config).not_to have_key('display_name')
        expect(config).not_to have_key('ocsp_enabled')
        expect(config).not_to have_key('ocsp_fail_open')
        expect(config).not_to have_key('ocsp_query_all_servers')
        expect(config).not_to have_key('required_extensions')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_organizational_units: ['test-value'], backend: 'test-value', namespace: 'test-value', ocsp_ca_certificates: 'test-value', ocsp_servers_override: ['test-value'], token_bound_cidrs: ['test-value'], token_explicit_max_ttl: 3.14, token_max_ttl: 3.14, token_no_default_policy: true, token_num_uses: 3.14, token_period: 3.14, token_policies: ['test-value'], token_ttl: 3.14, token_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'full')
        expect(config).to have_key('allowed_organizational_units')
        expect(config).to have_key('backend')
        expect(config).to have_key('namespace')
        expect(config).to have_key('ocsp_ca_certificates')
        expect(config).to have_key('ocsp_servers_override')
        expect(config).to have_key('token_bound_cidrs')
        expect(config).to have_key('token_explicit_max_ttl')
        expect(config).to have_key('token_max_ttl')
        expect(config).to have_key('token_no_default_policy')
        expect(config).to have_key('token_num_uses')
        expect(config).to have_key('token_period')
        expect(config).to have_key('token_policies')
        expect(config).to have_key('token_ttl')
        expect(config).to have_key('token_type')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_organizational_units when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(allowed_organizational_units: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('allowed_organizational_units')
      end

      it 'omits allowed_organizational_units when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_organizational_units')
      end
      it 'includes backend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(backend: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('backend')
      end

      it 'omits backend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('backend')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes ocsp_ca_certificates when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(ocsp_ca_certificates: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('ocsp_ca_certificates')
      end

      it 'omits ocsp_ca_certificates when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('ocsp_ca_certificates')
      end
      it 'includes ocsp_servers_override when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(ocsp_servers_override: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('ocsp_servers_override')
      end

      it 'omits ocsp_servers_override when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('ocsp_servers_override')
      end
      it 'includes token_bound_cidrs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_bound_cidrs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_bound_cidrs')
      end

      it 'omits token_bound_cidrs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_bound_cidrs')
      end
      it 'includes token_explicit_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_explicit_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_explicit_max_ttl')
      end

      it 'omits token_explicit_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_explicit_max_ttl')
      end
      it 'includes token_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_max_ttl')
      end

      it 'omits token_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_max_ttl')
      end
      it 'includes token_no_default_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_no_default_policy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_no_default_policy')
      end

      it 'omits token_no_default_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_no_default_policy')
      end
      it 'includes token_num_uses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_num_uses: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_num_uses')
      end

      it 'omits token_num_uses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_num_uses')
      end
      it 'includes token_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_period')
      end

      it 'omits token_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_period')
      end
      it 'includes token_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_policies')
      end

      it 'omits token_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_policies')
      end
      it 'includes token_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_ttl')
      end

      it 'omits token_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_ttl')
      end
      it 'includes token_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('opt', required_attrs.merge(token_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'opt')
        expect(config).to have_key('token_type')
      end

      it 'omits token_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts token_no_default_policy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(token_no_default_policy: val)
          synth.vault_cert_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_cert_auth_backend_role', "bool_#{val}")
          expect(config['token_no_default_policy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_cert_auth_backend_role', 'typed')
        expect(config['certificate']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_cert_auth_backend_role('first', required_attrs)
        synth.vault_cert_auth_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_cert_auth_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_cert_auth_backend_role,
    method: :vault_cert_auth_backend_role,
    required_attrs: { certificate: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :allowed_common_names, :allowed_dns_sans, :allowed_email_sans, :allowed_names, :allowed_uri_sans, :display_name, :ocsp_enabled, :ocsp_fail_open, :ocsp_query_all_servers, :required_extensions],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:token_no_default_policy]
end
