# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_raft_snapshot_agent_config resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultRaftSnapshotAgentConfig do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { interval_seconds: 3.14, name: 'test-value', path_prefix: 'test-value', storage_type: 'test-value' } }

  describe ':vault_raft_snapshot_agent_config' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'test')
        validate_required_attributes(config, [:interval_seconds, :name, :path_prefix, :storage_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_raft_snapshot_agent_config('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_raft_snapshot_agent_config)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_raft_snapshot_agent_config('test', required_attrs)

        expect(ref.id).to eq("${vault_raft_snapshot_agent_config.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ aws_access_key_id: 'test-value', aws_s3_bucket: 'test-value', aws_s3_disable_tls: true, aws_s3_enable_kms: true, aws_s3_endpoint: 'test-value', aws_s3_force_path_style: true, aws_s3_kms_key: 'test-value', aws_s3_region: 'test-value', aws_s3_server_side_encryption: true, aws_secret_access_key: 'test-value', aws_session_token: 'test-value', azure_account_key: 'test-value', azure_account_name: 'test-value', azure_blob_environment: 'test-value', azure_container_name: 'test-value', azure_endpoint: 'test-value', file_prefix: 'test-value', google_disable_tls: true, google_endpoint: 'test-value', google_gcs_bucket: 'test-value', google_service_account_key: 'test-value', local_max_space: 3.14, namespace: 'test-value', retain: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'full')
        expect(config).to have_key('aws_access_key_id')
        expect(config).to have_key('aws_s3_bucket')
        expect(config).to have_key('aws_s3_disable_tls')
        expect(config).to have_key('aws_s3_enable_kms')
        expect(config).to have_key('aws_s3_endpoint')
        expect(config).to have_key('aws_s3_force_path_style')
        expect(config).to have_key('aws_s3_kms_key')
        expect(config).to have_key('aws_s3_region')
        expect(config).to have_key('aws_s3_server_side_encryption')
        expect(config).to have_key('aws_secret_access_key')
        expect(config).to have_key('aws_session_token')
        expect(config).to have_key('azure_account_key')
        expect(config).to have_key('azure_account_name')
        expect(config).to have_key('azure_blob_environment')
        expect(config).to have_key('azure_container_name')
        expect(config).to have_key('azure_endpoint')
        expect(config).to have_key('file_prefix')
        expect(config).to have_key('google_disable_tls')
        expect(config).to have_key('google_endpoint')
        expect(config).to have_key('google_gcs_bucket')
        expect(config).to have_key('google_service_account_key')
        expect(config).to have_key('local_max_space')
        expect(config).to have_key('namespace')
        expect(config).to have_key('retain')
      end
    end

    context 'optional attributes' do
      it 'includes aws_access_key_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_access_key_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_access_key_id')
      end

      it 'omits aws_access_key_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_access_key_id')
      end
      it 'includes aws_s3_bucket when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_bucket: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_bucket')
      end

      it 'omits aws_s3_bucket when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_bucket')
      end
      it 'includes aws_s3_disable_tls when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_disable_tls: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_disable_tls')
      end

      it 'omits aws_s3_disable_tls when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_disable_tls')
      end
      it 'includes aws_s3_enable_kms when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_enable_kms: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_enable_kms')
      end

      it 'omits aws_s3_enable_kms when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_enable_kms')
      end
      it 'includes aws_s3_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_endpoint')
      end

      it 'omits aws_s3_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_endpoint')
      end
      it 'includes aws_s3_force_path_style when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_force_path_style: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_force_path_style')
      end

      it 'omits aws_s3_force_path_style when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_force_path_style')
      end
      it 'includes aws_s3_kms_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_kms_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_kms_key')
      end

      it 'omits aws_s3_kms_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_kms_key')
      end
      it 'includes aws_s3_region when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_region: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_region')
      end

      it 'omits aws_s3_region when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_region')
      end
      it 'includes aws_s3_server_side_encryption when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_s3_server_side_encryption: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_s3_server_side_encryption')
      end

      it 'omits aws_s3_server_side_encryption when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_s3_server_side_encryption')
      end
      it 'includes aws_secret_access_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_secret_access_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_secret_access_key')
      end

      it 'omits aws_secret_access_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_secret_access_key')
      end
      it 'includes aws_session_token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(aws_session_token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('aws_session_token')
      end

      it 'omits aws_session_token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('aws_session_token')
      end
      it 'includes azure_account_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(azure_account_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('azure_account_key')
      end

      it 'omits azure_account_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('azure_account_key')
      end
      it 'includes azure_account_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(azure_account_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('azure_account_name')
      end

      it 'omits azure_account_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('azure_account_name')
      end
      it 'includes azure_blob_environment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(azure_blob_environment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('azure_blob_environment')
      end

      it 'omits azure_blob_environment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('azure_blob_environment')
      end
      it 'includes azure_container_name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(azure_container_name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('azure_container_name')
      end

      it 'omits azure_container_name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('azure_container_name')
      end
      it 'includes azure_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(azure_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('azure_endpoint')
      end

      it 'omits azure_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('azure_endpoint')
      end
      it 'includes file_prefix when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(file_prefix: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('file_prefix')
      end

      it 'omits file_prefix when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('file_prefix')
      end
      it 'includes google_disable_tls when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(google_disable_tls: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('google_disable_tls')
      end

      it 'omits google_disable_tls when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('google_disable_tls')
      end
      it 'includes google_endpoint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(google_endpoint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('google_endpoint')
      end

      it 'omits google_endpoint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('google_endpoint')
      end
      it 'includes google_gcs_bucket when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(google_gcs_bucket: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('google_gcs_bucket')
      end

      it 'omits google_gcs_bucket when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('google_gcs_bucket')
      end
      it 'includes google_service_account_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(google_service_account_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('google_service_account_key')
      end

      it 'omits google_service_account_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('google_service_account_key')
      end
      it 'includes local_max_space when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(local_max_space: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('local_max_space')
      end

      it 'omits local_max_space when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('local_max_space')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes retain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('opt', required_attrs.merge(retain: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'opt')
        expect(config).to have_key('retain')
      end

      it 'omits retain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'minimal')
        expect(config).not_to have_key('retain')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts aws_s3_disable_tls=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(aws_s3_disable_tls: val)
          synth.vault_raft_snapshot_agent_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', "bool_#{val}")
          expect(config['aws_s3_disable_tls']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts aws_s3_enable_kms=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(aws_s3_enable_kms: val)
          synth.vault_raft_snapshot_agent_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', "bool_#{val}")
          expect(config['aws_s3_enable_kms']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts aws_s3_force_path_style=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(aws_s3_force_path_style: val)
          synth.vault_raft_snapshot_agent_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', "bool_#{val}")
          expect(config['aws_s3_force_path_style']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts aws_s3_server_side_encryption=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(aws_s3_server_side_encryption: val)
          synth.vault_raft_snapshot_agent_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', "bool_#{val}")
          expect(config['aws_s3_server_side_encryption']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts google_disable_tls=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(google_disable_tls: val)
          synth.vault_raft_snapshot_agent_config("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', "bool_#{val}")
          expect(config['google_disable_tls']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_raft_snapshot_agent_config', 'typed')
        expect(config['interval_seconds']).to be_a(Float)
        expect(config['name']).to be_a(String)
        expect(config['path_prefix']).to be_a(String)
        expect(config['storage_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_raft_snapshot_agent_config('first', required_attrs)
        synth.vault_raft_snapshot_agent_config('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_raft_snapshot_agent_config')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_raft_snapshot_agent_config,
    method: :vault_raft_snapshot_agent_config,
    required_attrs: { interval_seconds: 3.14, name: 'test-value', path_prefix: 'test-value', storage_type: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:aws_s3_disable_tls, :aws_s3_enable_kms, :aws_s3_force_path_style, :aws_s3_server_side_encryption, :google_disable_tls]
end
