# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_consul_secret_backend resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultConsulSecretBackend do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { address: 'test-value' } }

  describe ':vault_consul_secret_backend' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'test')
        validate_required_attributes(config, [:address])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_consul_secret_backend('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_consul_secret_backend)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_consul_secret_backend('test', required_attrs)

        expect(ref.id).to eq("${vault_consul_secret_backend.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ bootstrap: true, ca_cert: 'test-value', client_cert: 'test-value', client_key: 'test-value', default_lease_ttl_seconds: 3.14, description: 'test-value', disable_remount: true, local: true, max_lease_ttl_seconds: 3.14, namespace: 'test-value', path: 'test-value', scheme: 'test-value', token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'full')
        expect(config).to have_key('bootstrap')
        expect(config).to have_key('ca_cert')
        expect(config).to have_key('client_cert')
        expect(config).to have_key('client_key')
        expect(config).to have_key('default_lease_ttl_seconds')
        expect(config).to have_key('description')
        expect(config).to have_key('disable_remount')
        expect(config).to have_key('local')
        expect(config).to have_key('max_lease_ttl_seconds')
        expect(config).to have_key('namespace')
        expect(config).to have_key('path')
        expect(config).to have_key('scheme')
        expect(config).to have_key('token')
      end
    end

    context 'optional attributes' do
      it 'includes bootstrap when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(bootstrap: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('bootstrap')
      end

      it 'omits bootstrap when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('bootstrap')
      end
      it 'includes ca_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(ca_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('ca_cert')
      end

      it 'omits ca_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('ca_cert')
      end
      it 'includes client_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(client_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('client_cert')
      end

      it 'omits client_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('client_cert')
      end
      it 'includes client_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(client_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('client_key')
      end

      it 'omits client_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('client_key')
      end
      it 'includes default_lease_ttl_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(default_lease_ttl_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('default_lease_ttl_seconds')
      end

      it 'omits default_lease_ttl_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('default_lease_ttl_seconds')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes disable_remount when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(disable_remount: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('disable_remount')
      end

      it 'omits disable_remount when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('disable_remount')
      end
      it 'includes local when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(local: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('local')
      end

      it 'omits local when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('local')
      end
      it 'includes max_lease_ttl_seconds when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(max_lease_ttl_seconds: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('max_lease_ttl_seconds')
      end

      it 'omits max_lease_ttl_seconds when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('max_lease_ttl_seconds')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('path')
      end

      it 'omits path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('path')
      end
      it 'includes scheme when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(scheme: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('scheme')
      end

      it 'omits scheme when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('scheme')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'minimal')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:client_cert, :client_key, :token]
        expect(sensitive_fields).to include(:client_cert)
        expect(sensitive_fields).to include(:client_key)
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts bootstrap=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(bootstrap: val)
          synth.vault_consul_secret_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_consul_secret_backend', "bool_#{val}")
          expect(config['bootstrap']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_remount=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_remount: val)
          synth.vault_consul_secret_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_consul_secret_backend', "bool_#{val}")
          expect(config['disable_remount']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts local=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(local: val)
          synth.vault_consul_secret_backend("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_consul_secret_backend', "bool_#{val}")
          expect(config['local']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_consul_secret_backend', 'typed')
        expect(config['address']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_consul_secret_backend('first', required_attrs)
        synth.vault_consul_secret_backend('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_consul_secret_backend')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_consul_secret_backend,
    method: :vault_consul_secret_backend,
    required_attrs: { address: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [:client_cert, :client_key, :token],
    immutable_fields: [],
    boolean_fields: [:bootstrap, :disable_remount, :local]
end
