# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_github_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultGithubUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { user: 'test-value' } }

  describe ':vault_github_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_github_user', 'test')
        validate_required_attributes(config, [:user])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_github_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_github_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_github_user('test', required_attrs)

        expect(ref.id).to eq("${vault_github_user.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ backend: 'test-value', namespace: 'test-value', policies: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_github_user', 'full')
        expect(config).to have_key('backend')
        expect(config).to have_key('namespace')
        expect(config).to have_key('policies')
      end
    end

    context 'optional attributes' do
      it 'includes backend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('opt', required_attrs.merge(backend: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_github_user', 'opt')
        expect(config).to have_key('backend')
      end

      it 'omits backend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_github_user', 'minimal')
        expect(config).not_to have_key('backend')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_github_user', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_github_user', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('opt', required_attrs.merge(policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_github_user', 'opt')
        expect(config).to have_key('policies')
      end

      it 'omits policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_github_user', 'minimal')
        expect(config).not_to have_key('policies')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_github_user', 'typed')
        expect(config['user']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_github_user('first', required_attrs)
        synth.vault_github_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_github_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_github_user,
    method: :vault_github_user,
    required_attrs: { user: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
