# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_mfa_totp resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultMfaTotp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { issuer: 'test-value', name: 'test-value' } }

  describe ':vault_mfa_totp' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'test')
        validate_required_attributes(config, [:issuer, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_mfa_totp('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_mfa_totp)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_mfa_totp('test', required_attrs)

        expect(ref.id).to eq("${vault_mfa_totp.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ algorithm: 'test-value', digits: 3.14, key_size: 3.14, namespace: 'test-value', period: 3.14, qr_size: 3.14, skew: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_mfa_totp', 'full')
        expect(config).to have_key('algorithm')
        expect(config).to have_key('digits')
        expect(config).to have_key('key_size')
        expect(config).to have_key('namespace')
        expect(config).to have_key('period')
        expect(config).to have_key('qr_size')
        expect(config).to have_key('skew')
      end
    end

    context 'optional attributes' do
      it 'includes algorithm when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(algorithm: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('algorithm')
      end

      it 'omits algorithm when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('algorithm')
      end
      it 'includes digits when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(digits: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('digits')
      end

      it 'omits digits when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('digits')
      end
      it 'includes key_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(key_size: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('key_size')
      end

      it 'omits key_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('key_size')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('period')
      end

      it 'omits period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('period')
      end
      it 'includes qr_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(qr_size: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('qr_size')
      end

      it 'omits qr_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('qr_size')
      end
      it 'includes skew when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('opt', required_attrs.merge(skew: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'opt')
        expect(config).to have_key('skew')
      end

      it 'omits skew when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_mfa_totp', 'minimal')
        expect(config).not_to have_key('skew')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_mfa_totp', 'typed')
        expect(config['issuer']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_mfa_totp('first', required_attrs)
        synth.vault_mfa_totp('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_mfa_totp')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_mfa_totp,
    method: :vault_mfa_totp,
    required_attrs: { issuer: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
