# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_ad_secret_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultAdSecretRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value', role: 'test-value', service_account_name: 'test-value' } }

  describe ':vault_ad_secret_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_ad_secret_role', 'test')
        validate_required_attributes(config, [:backend, :role, :service_account_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_ad_secret_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_ad_secret_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_ad_secret_role('test', required_attrs)

        expect(ref.id).to eq("${vault_ad_secret_role.test.id}")
        expect(ref.last_vault_rotation).to eq("${vault_ad_secret_role.test.last_vault_rotation}")
        expect(ref.password_last_set).to eq("${vault_ad_secret_role.test.password_last_set}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ad_secret_role', 'test')
        expect(config).not_to have_key('last_vault_rotation')
        expect(config).not_to have_key('password_last_set')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ namespace: 'test-value', ttl: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ad_secret_role', 'full')
        expect(config).to have_key('namespace')
        expect(config).to have_key('ttl')
      end
    end

    context 'optional attributes' do
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ad_secret_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ad_secret_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('opt', required_attrs.merge(ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ad_secret_role', 'opt')
        expect(config).to have_key('ttl')
      end

      it 'omits ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ad_secret_role', 'minimal')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ad_secret_role', 'typed')
        expect(config['backend']).to be_a(String)
        expect(config['role']).to be_a(String)
        expect(config['service_account_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ad_secret_role('first', required_attrs)
        synth.vault_ad_secret_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_ad_secret_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_ad_secret_role,
    method: :vault_ad_secret_role,
    required_attrs: { backend: 'test-value', role: 'test-value', service_account_name: 'test-value' },
    expected_outputs: [:id, :last_vault_rotation, :password_last_set],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
