# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_ldap_secret_backend_library_set resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultLdapSecretBackendLibrarySet do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', service_account_names: ['test-value'] } }

  describe ':vault_ldap_secret_backend_library_set' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'test')
        validate_required_attributes(config, [:name, :service_account_names])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_ldap_secret_backend_library_set('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_ldap_secret_backend_library_set)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_ldap_secret_backend_library_set('test', required_attrs)

        expect(ref.id).to eq("${vault_ldap_secret_backend_library_set.test.id}")
        expect(ref.max_ttl).to eq("${vault_ldap_secret_backend_library_set.test.max_ttl}")
        expect(ref.ttl).to eq("${vault_ldap_secret_backend_library_set.test.ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'test')
        expect(config).not_to have_key('max_ttl')
        expect(config).not_to have_key('ttl')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disable_check_in_enforcement: true, mount: 'test-value', namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'full')
        expect(config).to have_key('disable_check_in_enforcement')
        expect(config).to have_key('mount')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes disable_check_in_enforcement when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('opt', required_attrs.merge(disable_check_in_enforcement: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'opt')
        expect(config).to have_key('disable_check_in_enforcement')
      end

      it 'omits disable_check_in_enforcement when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'minimal')
        expect(config).not_to have_key('disable_check_in_enforcement')
      end
      it 'includes mount when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('opt', required_attrs.merge(mount: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'opt')
        expect(config).to have_key('mount')
      end

      it 'omits mount when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'minimal')
        expect(config).not_to have_key('mount')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_check_in_enforcement=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_check_in_enforcement: val)
          synth.vault_ldap_secret_backend_library_set("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', "bool_#{val}")
          expect(config['disable_check_in_enforcement']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_ldap_secret_backend_library_set', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['service_account_names']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_ldap_secret_backend_library_set('first', required_attrs)
        synth.vault_ldap_secret_backend_library_set('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_ldap_secret_backend_library_set')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_ldap_secret_backend_library_set,
    method: :vault_ldap_secret_backend_library_set,
    required_attrs: { name: 'test-value', service_account_names: ['test-value'] },
    expected_outputs: [:id, :max_ttl, :ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_check_in_enforcement]
end
