# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_approle_auth_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultApproleAuthBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { role_name: 'test-value' } }

  describe ':vault_approle_auth_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'test')
        validate_required_attributes(config, [:role_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_approle_auth_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_approle_auth_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_approle_auth_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_approle_auth_backend_role.test.id}")
        expect(ref.role_id).to eq("${vault_approle_auth_backend_role.test.role_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'test')
        expect(config).not_to have_key('role_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ backend: 'test-value', bind_secret_id: true, namespace: 'test-value', secret_id_bound_cidrs: ['test-value'], secret_id_num_uses: 3.14, secret_id_ttl: 3.14, token_bound_cidrs: ['test-value'], token_explicit_max_ttl: 3.14, token_max_ttl: 3.14, token_no_default_policy: true, token_num_uses: 3.14, token_period: 3.14, token_policies: ['test-value'], token_ttl: 3.14, token_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'full')
        expect(config).to have_key('backend')
        expect(config).to have_key('bind_secret_id')
        expect(config).to have_key('namespace')
        expect(config).to have_key('secret_id_bound_cidrs')
        expect(config).to have_key('secret_id_num_uses')
        expect(config).to have_key('secret_id_ttl')
        expect(config).to have_key('token_bound_cidrs')
        expect(config).to have_key('token_explicit_max_ttl')
        expect(config).to have_key('token_max_ttl')
        expect(config).to have_key('token_no_default_policy')
        expect(config).to have_key('token_num_uses')
        expect(config).to have_key('token_period')
        expect(config).to have_key('token_policies')
        expect(config).to have_key('token_ttl')
        expect(config).to have_key('token_type')
      end
    end

    context 'optional attributes' do
      it 'includes backend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(backend: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('backend')
      end

      it 'omits backend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('backend')
      end
      it 'includes bind_secret_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(bind_secret_id: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('bind_secret_id')
      end

      it 'omits bind_secret_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('bind_secret_id')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes secret_id_bound_cidrs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(secret_id_bound_cidrs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('secret_id_bound_cidrs')
      end

      it 'omits secret_id_bound_cidrs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('secret_id_bound_cidrs')
      end
      it 'includes secret_id_num_uses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(secret_id_num_uses: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('secret_id_num_uses')
      end

      it 'omits secret_id_num_uses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('secret_id_num_uses')
      end
      it 'includes secret_id_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(secret_id_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('secret_id_ttl')
      end

      it 'omits secret_id_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('secret_id_ttl')
      end
      it 'includes token_bound_cidrs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_bound_cidrs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_bound_cidrs')
      end

      it 'omits token_bound_cidrs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_bound_cidrs')
      end
      it 'includes token_explicit_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_explicit_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_explicit_max_ttl')
      end

      it 'omits token_explicit_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_explicit_max_ttl')
      end
      it 'includes token_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_max_ttl')
      end

      it 'omits token_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_max_ttl')
      end
      it 'includes token_no_default_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_no_default_policy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_no_default_policy')
      end

      it 'omits token_no_default_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_no_default_policy')
      end
      it 'includes token_num_uses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_num_uses: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_num_uses')
      end

      it 'omits token_num_uses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_num_uses')
      end
      it 'includes token_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_period')
      end

      it 'omits token_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_period')
      end
      it 'includes token_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_policies')
      end

      it 'omits token_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_policies')
      end
      it 'includes token_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_ttl')
      end

      it 'omits token_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_ttl')
      end
      it 'includes token_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('opt', required_attrs.merge(token_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'opt')
        expect(config).to have_key('token_type')
      end

      it 'omits token_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts bind_secret_id=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(bind_secret_id: val)
          synth.vault_approle_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_approle_auth_backend_role', "bool_#{val}")
          expect(config['bind_secret_id']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts token_no_default_policy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(token_no_default_policy: val)
          synth.vault_approle_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_approle_auth_backend_role', "bool_#{val}")
          expect(config['token_no_default_policy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_approle_auth_backend_role', 'typed')
        expect(config['role_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_approle_auth_backend_role('first', required_attrs)
        synth.vault_approle_auth_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_approle_auth_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_approle_auth_backend_role,
    method: :vault_approle_auth_backend_role,
    required_attrs: { role_name: 'test-value' },
    expected_outputs: [:id, :role_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:bind_secret_id, :token_no_default_policy]
end
