# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_aws_secret_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultAwsSecretBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value', credential_type: 'test-value', name: 'test-value' } }

  describe ':vault_aws_secret_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'test')
        validate_required_attributes(config, [:backend, :credential_type, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_aws_secret_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_aws_secret_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_aws_secret_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_aws_secret_backend_role.test.id}")
        expect(ref.default_sts_ttl).to eq("${vault_aws_secret_backend_role.test.default_sts_ttl}")
        expect(ref.max_sts_ttl).to eq("${vault_aws_secret_backend_role.test.max_sts_ttl}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'test')
        expect(config).not_to have_key('default_sts_ttl')
        expect(config).not_to have_key('max_sts_ttl')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ external_id: 'test-value', iam_groups: ['test-value'], iam_tags: { 'key1' => 'val1' }, namespace: 'test-value', permissions_boundary_arn: 'test-value', policy_arns: ['test-value'], policy_document: 'test-value', role_arns: ['test-value'], session_tags: { 'key1' => 'val1' }, user_path: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'full')
        expect(config).to have_key('external_id')
        expect(config).to have_key('iam_groups')
        expect(config).to have_key('iam_tags')
        expect(config).to have_key('namespace')
        expect(config).to have_key('permissions_boundary_arn')
        expect(config).to have_key('policy_arns')
        expect(config).to have_key('policy_document')
        expect(config).to have_key('role_arns')
        expect(config).to have_key('session_tags')
        expect(config).to have_key('user_path')
      end
    end

    context 'optional attributes' do
      it 'includes external_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(external_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('external_id')
      end

      it 'omits external_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('external_id')
      end
      it 'includes iam_groups when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(iam_groups: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('iam_groups')
      end

      it 'omits iam_groups when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('iam_groups')
      end
      it 'includes iam_tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(iam_tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('iam_tags')
      end

      it 'omits iam_tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('iam_tags')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes permissions_boundary_arn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(permissions_boundary_arn: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('permissions_boundary_arn')
      end

      it 'omits permissions_boundary_arn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('permissions_boundary_arn')
      end
      it 'includes policy_arns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(policy_arns: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('policy_arns')
      end

      it 'omits policy_arns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('policy_arns')
      end
      it 'includes policy_document when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(policy_document: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('policy_document')
      end

      it 'omits policy_document when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('policy_document')
      end
      it 'includes role_arns when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(role_arns: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('role_arns')
      end

      it 'omits role_arns when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('role_arns')
      end
      it 'includes session_tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(session_tags: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('session_tags')
      end

      it 'omits session_tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('session_tags')
      end
      it 'includes user_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('opt', required_attrs.merge(user_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'opt')
        expect(config).to have_key('user_path')
      end

      it 'omits user_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'minimal')
        expect(config).not_to have_key('user_path')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_aws_secret_backend_role', 'typed')
        expect(config['backend']).to be_a(String)
        expect(config['credential_type']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_aws_secret_backend_role('first', required_attrs)
        synth.vault_aws_secret_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_aws_secret_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_aws_secret_backend_role,
    method: :vault_aws_secret_backend_role,
    required_attrs: { backend: 'test-value', credential_type: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :default_sts_ttl, :max_sts_ttl],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
