# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_token_auth_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultTokenAuthBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { role_name: 'test-value' } }

  describe ':vault_token_auth_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'test')
        validate_required_attributes(config, [:role_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_token_auth_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_token_auth_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_token_auth_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_token_auth_backend_role.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_entity_aliases: ['test-value'], allowed_policies: ['test-value'], allowed_policies_glob: ['test-value'], disallowed_policies: ['test-value'], disallowed_policies_glob: ['test-value'], namespace: 'test-value', orphan: true, path_suffix: 'test-value', renewable: true, token_bound_cidrs: ['test-value'], token_explicit_max_ttl: 3.14, token_max_ttl: 3.14, token_no_default_policy: true, token_num_uses: 3.14, token_period: 3.14, token_policies: ['test-value'], token_ttl: 3.14, token_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'full')
        expect(config).to have_key('allowed_entity_aliases')
        expect(config).to have_key('allowed_policies')
        expect(config).to have_key('allowed_policies_glob')
        expect(config).to have_key('disallowed_policies')
        expect(config).to have_key('disallowed_policies_glob')
        expect(config).to have_key('namespace')
        expect(config).to have_key('orphan')
        expect(config).to have_key('path_suffix')
        expect(config).to have_key('renewable')
        expect(config).to have_key('token_bound_cidrs')
        expect(config).to have_key('token_explicit_max_ttl')
        expect(config).to have_key('token_max_ttl')
        expect(config).to have_key('token_no_default_policy')
        expect(config).to have_key('token_num_uses')
        expect(config).to have_key('token_period')
        expect(config).to have_key('token_policies')
        expect(config).to have_key('token_ttl')
        expect(config).to have_key('token_type')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_entity_aliases when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(allowed_entity_aliases: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('allowed_entity_aliases')
      end

      it 'omits allowed_entity_aliases when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_entity_aliases')
      end
      it 'includes allowed_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(allowed_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('allowed_policies')
      end

      it 'omits allowed_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_policies')
      end
      it 'includes allowed_policies_glob when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(allowed_policies_glob: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('allowed_policies_glob')
      end

      it 'omits allowed_policies_glob when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_policies_glob')
      end
      it 'includes disallowed_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(disallowed_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('disallowed_policies')
      end

      it 'omits disallowed_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('disallowed_policies')
      end
      it 'includes disallowed_policies_glob when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(disallowed_policies_glob: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('disallowed_policies_glob')
      end

      it 'omits disallowed_policies_glob when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('disallowed_policies_glob')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes orphan when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(orphan: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('orphan')
      end

      it 'omits orphan when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('orphan')
      end
      it 'includes path_suffix when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(path_suffix: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('path_suffix')
      end

      it 'omits path_suffix when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('path_suffix')
      end
      it 'includes renewable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(renewable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('renewable')
      end

      it 'omits renewable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('renewable')
      end
      it 'includes token_bound_cidrs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_bound_cidrs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_bound_cidrs')
      end

      it 'omits token_bound_cidrs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_bound_cidrs')
      end
      it 'includes token_explicit_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_explicit_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_explicit_max_ttl')
      end

      it 'omits token_explicit_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_explicit_max_ttl')
      end
      it 'includes token_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_max_ttl')
      end

      it 'omits token_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_max_ttl')
      end
      it 'includes token_no_default_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_no_default_policy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_no_default_policy')
      end

      it 'omits token_no_default_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_no_default_policy')
      end
      it 'includes token_num_uses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_num_uses: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_num_uses')
      end

      it 'omits token_num_uses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_num_uses')
      end
      it 'includes token_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_period')
      end

      it 'omits token_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_period')
      end
      it 'includes token_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_policies')
      end

      it 'omits token_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_policies')
      end
      it 'includes token_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_ttl')
      end

      it 'omits token_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_ttl')
      end
      it 'includes token_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('opt', required_attrs.merge(token_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'opt')
        expect(config).to have_key('token_type')
      end

      it 'omits token_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts orphan=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(orphan: val)
          synth.vault_token_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_token_auth_backend_role', "bool_#{val}")
          expect(config['orphan']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts renewable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(renewable: val)
          synth.vault_token_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_token_auth_backend_role', "bool_#{val}")
          expect(config['renewable']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts token_no_default_policy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(token_no_default_policy: val)
          synth.vault_token_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_token_auth_backend_role', "bool_#{val}")
          expect(config['token_no_default_policy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_token_auth_backend_role', 'typed')
        expect(config['role_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_token_auth_backend_role('first', required_attrs)
        synth.vault_token_auth_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_token_auth_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_token_auth_backend_role,
    method: :vault_token_auth_backend_role,
    required_attrs: { role_name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:orphan, :renewable, :token_no_default_policy]
end
