# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_jwt_auth_backend_role resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultJwtAuthBackendRole do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { role_name: 'test-value', user_claim: 'test-value' } }

  describe ':vault_jwt_auth_backend_role' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'test')
        validate_required_attributes(config, [:role_name, :user_claim])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_jwt_auth_backend_role('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_jwt_auth_backend_role)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_jwt_auth_backend_role('test', required_attrs)

        expect(ref.id).to eq("${vault_jwt_auth_backend_role.test.id}")
        expect(ref.bound_claims_type).to eq("${vault_jwt_auth_backend_role.test.bound_claims_type}")
        expect(ref.role_type).to eq("${vault_jwt_auth_backend_role.test.role_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'test')
        expect(config).not_to have_key('bound_claims_type')
        expect(config).not_to have_key('role_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_redirect_uris: ['test-value'], backend: 'test-value', bound_audiences: ['test-value'], bound_claims: { 'key1' => 'val1' }, bound_subject: 'test-value', claim_mappings: { 'key1' => 'val1' }, clock_skew_leeway: 3.14, disable_bound_claims_parsing: true, expiration_leeway: 3.14, groups_claim: 'test-value', max_age: 3.14, namespace: 'test-value', not_before_leeway: 3.14, oidc_scopes: ['test-value'], token_bound_cidrs: ['test-value'], token_explicit_max_ttl: 3.14, token_max_ttl: 3.14, token_no_default_policy: true, token_num_uses: 3.14, token_period: 3.14, token_policies: ['test-value'], token_ttl: 3.14, token_type: 'test-value', user_claim_json_pointer: true, verbose_oidc_logging: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'full')
        expect(config).to have_key('allowed_redirect_uris')
        expect(config).to have_key('backend')
        expect(config).to have_key('bound_audiences')
        expect(config).to have_key('bound_claims')
        expect(config).to have_key('bound_subject')
        expect(config).to have_key('claim_mappings')
        expect(config).to have_key('clock_skew_leeway')
        expect(config).to have_key('disable_bound_claims_parsing')
        expect(config).to have_key('expiration_leeway')
        expect(config).to have_key('groups_claim')
        expect(config).to have_key('max_age')
        expect(config).to have_key('namespace')
        expect(config).to have_key('not_before_leeway')
        expect(config).to have_key('oidc_scopes')
        expect(config).to have_key('token_bound_cidrs')
        expect(config).to have_key('token_explicit_max_ttl')
        expect(config).to have_key('token_max_ttl')
        expect(config).to have_key('token_no_default_policy')
        expect(config).to have_key('token_num_uses')
        expect(config).to have_key('token_period')
        expect(config).to have_key('token_policies')
        expect(config).to have_key('token_ttl')
        expect(config).to have_key('token_type')
        expect(config).to have_key('user_claim_json_pointer')
        expect(config).to have_key('verbose_oidc_logging')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_redirect_uris when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(allowed_redirect_uris: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('allowed_redirect_uris')
      end

      it 'omits allowed_redirect_uris when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('allowed_redirect_uris')
      end
      it 'includes backend when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(backend: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('backend')
      end

      it 'omits backend when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('backend')
      end
      it 'includes bound_audiences when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(bound_audiences: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('bound_audiences')
      end

      it 'omits bound_audiences when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('bound_audiences')
      end
      it 'includes bound_claims when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(bound_claims: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('bound_claims')
      end

      it 'omits bound_claims when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('bound_claims')
      end
      it 'includes bound_subject when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(bound_subject: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('bound_subject')
      end

      it 'omits bound_subject when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('bound_subject')
      end
      it 'includes claim_mappings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(claim_mappings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('claim_mappings')
      end

      it 'omits claim_mappings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('claim_mappings')
      end
      it 'includes clock_skew_leeway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(clock_skew_leeway: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('clock_skew_leeway')
      end

      it 'omits clock_skew_leeway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('clock_skew_leeway')
      end
      it 'includes disable_bound_claims_parsing when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(disable_bound_claims_parsing: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('disable_bound_claims_parsing')
      end

      it 'omits disable_bound_claims_parsing when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('disable_bound_claims_parsing')
      end
      it 'includes expiration_leeway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(expiration_leeway: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('expiration_leeway')
      end

      it 'omits expiration_leeway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('expiration_leeway')
      end
      it 'includes groups_claim when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(groups_claim: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('groups_claim')
      end

      it 'omits groups_claim when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('groups_claim')
      end
      it 'includes max_age when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(max_age: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('max_age')
      end

      it 'omits max_age when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('max_age')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes not_before_leeway when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(not_before_leeway: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('not_before_leeway')
      end

      it 'omits not_before_leeway when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('not_before_leeway')
      end
      it 'includes oidc_scopes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(oidc_scopes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('oidc_scopes')
      end

      it 'omits oidc_scopes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('oidc_scopes')
      end
      it 'includes token_bound_cidrs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_bound_cidrs: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_bound_cidrs')
      end

      it 'omits token_bound_cidrs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_bound_cidrs')
      end
      it 'includes token_explicit_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_explicit_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_explicit_max_ttl')
      end

      it 'omits token_explicit_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_explicit_max_ttl')
      end
      it 'includes token_max_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_max_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_max_ttl')
      end

      it 'omits token_max_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_max_ttl')
      end
      it 'includes token_no_default_policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_no_default_policy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_no_default_policy')
      end

      it 'omits token_no_default_policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_no_default_policy')
      end
      it 'includes token_num_uses when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_num_uses: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_num_uses')
      end

      it 'omits token_num_uses when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_num_uses')
      end
      it 'includes token_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_period')
      end

      it 'omits token_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_period')
      end
      it 'includes token_policies when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_policies: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_policies')
      end

      it 'omits token_policies when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_policies')
      end
      it 'includes token_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_ttl')
      end

      it 'omits token_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_ttl')
      end
      it 'includes token_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(token_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('token_type')
      end

      it 'omits token_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('token_type')
      end
      it 'includes user_claim_json_pointer when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(user_claim_json_pointer: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('user_claim_json_pointer')
      end

      it 'omits user_claim_json_pointer when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('user_claim_json_pointer')
      end
      it 'includes verbose_oidc_logging when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('opt', required_attrs.merge(verbose_oidc_logging: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'opt')
        expect(config).to have_key('verbose_oidc_logging')
      end

      it 'omits verbose_oidc_logging when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'minimal')
        expect(config).not_to have_key('verbose_oidc_logging')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disable_bound_claims_parsing=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_bound_claims_parsing: val)
          synth.vault_jwt_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', "bool_#{val}")
          expect(config['disable_bound_claims_parsing']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts token_no_default_policy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(token_no_default_policy: val)
          synth.vault_jwt_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', "bool_#{val}")
          expect(config['token_no_default_policy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts user_claim_json_pointer=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(user_claim_json_pointer: val)
          synth.vault_jwt_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', "bool_#{val}")
          expect(config['user_claim_json_pointer']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts verbose_oidc_logging=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(verbose_oidc_logging: val)
          synth.vault_jwt_auth_backend_role("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', "bool_#{val}")
          expect(config['verbose_oidc_logging']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_jwt_auth_backend_role', 'typed')
        expect(config['role_name']).to be_a(String)
        expect(config['user_claim']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_jwt_auth_backend_role('first', required_attrs)
        synth.vault_jwt_auth_backend_role('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_jwt_auth_backend_role')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_jwt_auth_backend_role,
    method: :vault_jwt_auth_backend_role,
    required_attrs: { role_name: 'test-value', user_claim: 'test-value' },
    expected_outputs: [:id, :bound_claims_type, :role_type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disable_bound_claims_parsing, :token_no_default_policy, :user_claim_json_pointer, :verbose_oidc_logging]
end
