# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_audit resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultAudit do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { options: { 'key1' => 'val1' }, type: 'test-value' } }

  describe ':vault_audit' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_audit', 'test')
        validate_required_attributes(config, [:options, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_audit('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_audit)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_audit('test', required_attrs)

        expect(ref.id).to eq("${vault_audit.test.id}")
        expect(ref.path).to eq("${vault_audit.test.path}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_audit', 'test')
        expect(config).not_to have_key('path')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', local: true, namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_audit', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('local')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_audit', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_audit', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes local when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('opt', required_attrs.merge(local: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_audit', 'opt')
        expect(config).to have_key('local')
      end

      it 'omits local when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_audit', 'minimal')
        expect(config).not_to have_key('local')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_audit', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_audit', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts local=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(local: val)
          synth.vault_audit("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_audit', "bool_#{val}")
          expect(config['local']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_audit', 'typed')
        expect(config['options']).to be_a(Hash)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_audit('first', required_attrs)
        synth.vault_audit('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_audit')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_audit,
    method: :vault_audit,
    required_attrs: { options: { 'key1' => 'val1' }, type: 'test-value' },
    expected_outputs: [:id, :path],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:local]
end
