# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_identity_mfa_login_enforcement resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultIdentityMfaLoginEnforcement do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { mfa_method_ids: ['test-value'], name: 'test-value' } }

  describe ':vault_identity_mfa_login_enforcement' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'test')
        validate_required_attributes(config, [:mfa_method_ids, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_identity_mfa_login_enforcement('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_identity_mfa_login_enforcement)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_identity_mfa_login_enforcement('test', required_attrs)

        expect(ref.id).to eq("${vault_identity_mfa_login_enforcement.test.id}")
        expect(ref.namespace_id).to eq("${vault_identity_mfa_login_enforcement.test.namespace_id}")
        expect(ref.namespace_path).to eq("${vault_identity_mfa_login_enforcement.test.namespace_path}")
        expect(ref.uuid).to eq("${vault_identity_mfa_login_enforcement.test.uuid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'test')
        expect(config).not_to have_key('namespace_id')
        expect(config).not_to have_key('namespace_path')
        expect(config).not_to have_key('uuid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ auth_method_accessors: ['test-value'], auth_method_types: ['test-value'], identity_entity_ids: ['test-value'], identity_group_ids: ['test-value'], namespace: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'full')
        expect(config).to have_key('auth_method_accessors')
        expect(config).to have_key('auth_method_types')
        expect(config).to have_key('identity_entity_ids')
        expect(config).to have_key('identity_group_ids')
        expect(config).to have_key('namespace')
      end
    end

    context 'optional attributes' do
      it 'includes auth_method_accessors when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('opt', required_attrs.merge(auth_method_accessors: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'opt')
        expect(config).to have_key('auth_method_accessors')
      end

      it 'omits auth_method_accessors when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'minimal')
        expect(config).not_to have_key('auth_method_accessors')
      end
      it 'includes auth_method_types when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('opt', required_attrs.merge(auth_method_types: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'opt')
        expect(config).to have_key('auth_method_types')
      end

      it 'omits auth_method_types when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'minimal')
        expect(config).not_to have_key('auth_method_types')
      end
      it 'includes identity_entity_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('opt', required_attrs.merge(identity_entity_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'opt')
        expect(config).to have_key('identity_entity_ids')
      end

      it 'omits identity_entity_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'minimal')
        expect(config).not_to have_key('identity_entity_ids')
      end
      it 'includes identity_group_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('opt', required_attrs.merge(identity_group_ids: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'opt')
        expect(config).to have_key('identity_group_ids')
      end

      it 'omits identity_group_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'minimal')
        expect(config).not_to have_key('identity_group_ids')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'minimal')
        expect(config).not_to have_key('namespace')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_identity_mfa_login_enforcement', 'typed')
        expect(config['mfa_method_ids']).to be_a(Array)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_identity_mfa_login_enforcement('first', required_attrs)
        synth.vault_identity_mfa_login_enforcement('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_identity_mfa_login_enforcement')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_identity_mfa_login_enforcement,
    method: :vault_identity_mfa_login_enforcement,
    required_attrs: { mfa_method_ids: ['test-value'], name: 'test-value' },
    expected_outputs: [:id, :namespace_id, :namespace_path, :uuid],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
