# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_secrets_sync_vercel_destination resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultSecretsSyncVercelDestination do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { access_token: 'test-value', deployment_environments: ['test-value'], name: 'test-value', project_id: 'test-value' } }

  describe ':vault_secrets_sync_vercel_destination' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'test')
        validate_required_attributes(config, [:access_token, :deployment_environments, :name, :project_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_secrets_sync_vercel_destination('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_secrets_sync_vercel_destination)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_secrets_sync_vercel_destination('test', required_attrs)

        expect(ref.id).to eq("${vault_secrets_sync_vercel_destination.test.id}")
        expect(ref.secret_name_template).to eq("${vault_secrets_sync_vercel_destination.test.secret_name_template}")
        expect(ref.type).to eq("${vault_secrets_sync_vercel_destination.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'test')
        expect(config).not_to have_key('secret_name_template')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ granularity: 'test-value', namespace: 'test-value', team_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'full')
        expect(config).to have_key('granularity')
        expect(config).to have_key('namespace')
        expect(config).to have_key('team_id')
      end
    end

    context 'optional attributes' do
      it 'includes granularity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('opt', required_attrs.merge(granularity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'opt')
        expect(config).to have_key('granularity')
      end

      it 'omits granularity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'minimal')
        expect(config).not_to have_key('granularity')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes team_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('opt', required_attrs.merge(team_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'opt')
        expect(config).to have_key('team_id')
      end

      it 'omits team_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'minimal')
        expect(config).not_to have_key('team_id')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:access_token]
        expect(sensitive_fields).to include(:access_token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_secrets_sync_vercel_destination', 'typed')
        expect(config['access_token']).to be_a(String)
        expect(config['deployment_environments']).to be_a(Array)
        expect(config['name']).to be_a(String)
        expect(config['project_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_secrets_sync_vercel_destination('first', required_attrs)
        synth.vault_secrets_sync_vercel_destination('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_secrets_sync_vercel_destination')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_secrets_sync_vercel_destination,
    method: :vault_secrets_sync_vercel_destination,
    required_attrs: { access_token: 'test-value', deployment_environments: ['test-value'], name: 'test-value', project_id: 'test-value' },
    expected_outputs: [:id, :secret_name_template, :type],
    sensitive_fields: [:access_token],
    immutable_fields: [],
    boolean_fields: []
end
