# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a vault_transit_secret_backend_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::VaultTransitSecretBackendKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { backend: 'test-value', name: 'test-value' } }

  describe ':vault_transit_secret_backend_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'test')
        validate_required_attributes(config, [:backend, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_transit_secret_backend_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:vault_transit_secret_backend_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.vault_transit_secret_backend_key('test', required_attrs)

        expect(ref.id).to eq("${vault_transit_secret_backend_key.test.id}")
        expect(ref.auto_rotate_period).to eq("${vault_transit_secret_backend_key.test.auto_rotate_period}")
        expect(ref.keys).to eq("${vault_transit_secret_backend_key.test.keys}")
        expect(ref.latest_version).to eq("${vault_transit_secret_backend_key.test.latest_version}")
        expect(ref.min_available_version).to eq("${vault_transit_secret_backend_key.test.min_available_version}")
        expect(ref.supports_decryption).to eq("${vault_transit_secret_backend_key.test.supports_decryption}")
        expect(ref.supports_derivation).to eq("${vault_transit_secret_backend_key.test.supports_derivation}")
        expect(ref.supports_encryption).to eq("${vault_transit_secret_backend_key.test.supports_encryption}")
        expect(ref.supports_signing).to eq("${vault_transit_secret_backend_key.test.supports_signing}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'test')
        expect(config).not_to have_key('auto_rotate_period')
        expect(config).not_to have_key('keys')
        expect(config).not_to have_key('latest_version')
        expect(config).not_to have_key('min_available_version')
        expect(config).not_to have_key('supports_decryption')
        expect(config).not_to have_key('supports_derivation')
        expect(config).not_to have_key('supports_encryption')
        expect(config).not_to have_key('supports_signing')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allow_plaintext_backup: true, convergent_encryption: true, deletion_allowed: true, derived: true, exportable: true, hybrid_key_type_ec: 'test-value', hybrid_key_type_pqc: 'test-value', key_size: 3.14, min_decryption_version: 3.14, min_encryption_version: 3.14, namespace: 'test-value', parameter_set: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'full')
        expect(config).to have_key('allow_plaintext_backup')
        expect(config).to have_key('convergent_encryption')
        expect(config).to have_key('deletion_allowed')
        expect(config).to have_key('derived')
        expect(config).to have_key('exportable')
        expect(config).to have_key('hybrid_key_type_ec')
        expect(config).to have_key('hybrid_key_type_pqc')
        expect(config).to have_key('key_size')
        expect(config).to have_key('min_decryption_version')
        expect(config).to have_key('min_encryption_version')
        expect(config).to have_key('namespace')
        expect(config).to have_key('parameter_set')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes allow_plaintext_backup when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(allow_plaintext_backup: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('allow_plaintext_backup')
      end

      it 'omits allow_plaintext_backup when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('allow_plaintext_backup')
      end
      it 'includes convergent_encryption when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(convergent_encryption: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('convergent_encryption')
      end

      it 'omits convergent_encryption when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('convergent_encryption')
      end
      it 'includes deletion_allowed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(deletion_allowed: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('deletion_allowed')
      end

      it 'omits deletion_allowed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('deletion_allowed')
      end
      it 'includes derived when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(derived: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('derived')
      end

      it 'omits derived when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('derived')
      end
      it 'includes exportable when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(exportable: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('exportable')
      end

      it 'omits exportable when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('exportable')
      end
      it 'includes hybrid_key_type_ec when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(hybrid_key_type_ec: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('hybrid_key_type_ec')
      end

      it 'omits hybrid_key_type_ec when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('hybrid_key_type_ec')
      end
      it 'includes hybrid_key_type_pqc when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(hybrid_key_type_pqc: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('hybrid_key_type_pqc')
      end

      it 'omits hybrid_key_type_pqc when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('hybrid_key_type_pqc')
      end
      it 'includes key_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(key_size: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('key_size')
      end

      it 'omits key_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('key_size')
      end
      it 'includes min_decryption_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(min_decryption_version: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('min_decryption_version')
      end

      it 'omits min_decryption_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('min_decryption_version')
      end
      it 'includes min_encryption_version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(min_encryption_version: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('min_encryption_version')
      end

      it 'omits min_encryption_version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('min_encryption_version')
      end
      it 'includes namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('namespace')
      end

      it 'omits namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('namespace')
      end
      it 'includes parameter_set when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(parameter_set: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('parameter_set')
      end

      it 'omits parameter_set when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('parameter_set')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts allow_plaintext_backup=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(allow_plaintext_backup: val)
          synth.vault_transit_secret_backend_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_transit_secret_backend_key', "bool_#{val}")
          expect(config['allow_plaintext_backup']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts convergent_encryption=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(convergent_encryption: val)
          synth.vault_transit_secret_backend_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_transit_secret_backend_key', "bool_#{val}")
          expect(config['convergent_encryption']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts deletion_allowed=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(deletion_allowed: val)
          synth.vault_transit_secret_backend_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_transit_secret_backend_key', "bool_#{val}")
          expect(config['deletion_allowed']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts derived=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(derived: val)
          synth.vault_transit_secret_backend_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_transit_secret_backend_key', "bool_#{val}")
          expect(config['derived']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts exportable=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(exportable: val)
          synth.vault_transit_secret_backend_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'vault_transit_secret_backend_key', "bool_#{val}")
          expect(config['exportable']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'vault_transit_secret_backend_key', 'typed')
        expect(config['backend']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.vault_transit_secret_backend_key('first', required_attrs)
        synth.vault_transit_secret_backend_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'vault_transit_secret_backend_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :vault_transit_secret_backend_key,
    method: :vault_transit_secret_backend_key,
    required_attrs: { backend: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :auto_rotate_period, :keys, :latest_version, :min_available_version, :supports_decryption, :supports_derivation, :supports_encryption, :supports_signing],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:allow_plaintext_backup, :convergent_encryption, :deletion_allowed, :derived, :exportable]
end
